export const translationsEN = {
  welcome:
    "Welcome to the official registration platform. Please select the type of form you wish to complete.",
  contact: "Contact",
  about: "About",
  home: "Home",
  logout: "Logout",
  submit: "Submit",
  approved: "Read and approved",
  admin_space: "Admin area",
  champ: "* : Required field",
  champ2: "Information icon (mouse over)",
  choose_language: "Choose your language",
  cancel: "Cancel",
  academy_registration: "Academy Registration Request",
  academy_registration_desc: "Form to register and join the academy (U5-U9)",
  selection_tests: "Selection Tests",
  selection_tests_desc:
    "Form to register for the Academy's selection tests (U5-U21)",
  accident_report: "Accident Report",
  accident_report_desc:
    "Form to report a club-related accident or submit a recovery certificate",
  liability_waiver: "Responsability Waiver",
  liability_waiver_desc: "Liability waiver form for selection tests",
  admin_dashboard: "Dashboard",
  admin_documents: "Documents",
  admin_planning: "Planning",
  admin_members: "Members",
  admin_graphics: "Statistics",
  admin_settings: "Settings",
  admin_logout: "Logout",
  admin_panel: "Admin Panel",
  admin_rwdm: "RWDM Admin",
  privacy_policy: "Privacy Policy",
  terms_and_conditions: "Terms and Conditions",
  legal_notice: "Legal Notice",
  cookie_policy: "Cookie Policy",
  email_unavailable: "Email unavailable",
  legal_info: "Legal Information",
  all_rights_reserved: "All rights reserved.",
  footer_description:
    "The Academy is dedicated to developing young Belgian football talents. We are committed to providing a high-quality learning environment.",
  about_title: "About us",
  about_subtitle:
    "Discover our story, mission, and the team dedicated to developing young talents.",
  players_trained: "Professional players trained",
  years_experience: "Years of experience",
  national_trophies: "Teams involved",
  young_talents: "Young talents",
  tab_history: "History",
  tab_mission: "Mission",
  tab_approach: "Approach",
  history_title: "History",
  mission_title: "Our mission",
  approach_title: "Our approach",
  academies_title: "Our academies",
  rwdm_academy: "RWDM Aca.",
  bef_academy: "BEF Aca.",
  rfe_academy: "RFE Aca.",
  values_title: "Our values",
  team_title: "Our team",
  no_team_members:
    "There are currently no team members registered on the platform.",
  contact_title: "Contact Us",
  contact_description:
    "Have questions? Don't hesitate to get in touch. Our team is here to help.",
  send_us_message: "Send us a message",
  contact_name: "Name",
  contact_email: "Email",
  contact_subject: "Subject",
  contact_message: "Message",
  contact_submit: "Send Message",
  contact_office_hours: "Office Opening Hours",
  contact_address_title: "Our Address",
  contact_email_title: "Email",
  contact_info_title: "Information",
  contact_account_name: "Account Name",
  contact_vat_number: "VAT Number",
  contact_company_number: "Company Number",
  contact_closed: "Closed",
  how_to_find_us: "How to find us",
  day_lundi: "Monday",
  day_mardi: "Tuesday",
  day_mercredi: "Wednesday",
  day_jeudi: "Thursday",
  day_vendredi: "Friday",
  day_samedi: "Saturday",
  day_dimanche: "Sunday",
  closed: "Closed",
  contact_select_subject: "Choose a subject",
  contact_subject_registration: "Question about a registration request",
  contact_subject_selection: "Question about the selection tests",
  contact_subject_waiver: "Question about a liability waiver",
  contact_subject_accident: "Accident report",
  contact_subject_recruitment: "Recruitment",
  contact_subject_incident: "Incident",
  contact_subject_technical: "Technical issue",
  contact_subject_other: "Other",
  inbox: "Inbox",
  auth_title: "Authentication",
  auth_subtitle: "Access restricted to authorized personnel",
  auth_email_label: "Email",
  auth_email_placeholder: "your.email@rwdm.be",
  auth_password_label: "Password",
  auth_forgot_password: "Forgot password?",
  auth_login_button: "Log in",
  auth_logging_in: "Logging in...",
  auth_admin_note: "This page is reserved for administrators.",
  auth_login_success: "Login successful",
  auth_login_success_desc: "Welcome to the admin panel",
  auth_login_error: "Login error",
  auth_login_error_desc: "Please check your credentials.",
  season_selection: "Registration season",
  season_selection_desc:
    "Please select the season you want to register the player for",
  select_season_placeholder: "Select a season",

  // Académie
  academy_selection: "Academy",
  academy_selection_desc:
    "Please select the desired academy for the player's registration",
  select_academy_placeholder: "Select an academy",

  // Informations joueur
  player_info: "Player information",
  player_info_desc: "Please fill out all the information about the player",
  label_last_name: "Last Name *",
  label_first_name: "First Name *",
  label_birth_date: "Birth Date *",
  label_birth_place: "Birth Place *",
  label_address: "Address *",
  label_postal_code: "Postal Code *",
  label_city: "City *",
  label_current_club: "Current Club",
  tooltip_current_club:
    "If the player does not have a club, you can leave it blank.",
  label_category: "Category *",
  select_category_placeholder: "Select a category",

  // Responsables légaux
  legal_info_desc:
    "Please fill in the legal guardians' information for the player",
  primary_guardian: "Primary guardian",
  label_guardian_type: "Type *",
  select_type_placeholder: "Select type",
  option_father: "Father",
  option_mother: "Mother",
  option_legal_guardian: "Legal guardian",
  label_parent_last_name: "Last Name *",
  label_parent_first_name: "First Name *",
  label_parent_phone: "Phone *",
  label_parent_email: "Email *",
  label_parent_address: "Address *",
  label_parent_postal_code: "Postal Code *",
  label_parent_gsm: "Cell Phone",
  secondary_guardian_button: "Secondary guardian (optional)",

  // Consentement image
  consent_image: "Image consent",
  consent_image_desc: "Please provide your consent for the use of images",
  consent_image_label:
    "I agree that photos of my child may be taken and used for promotional purposes.",

  // Signature
  signature: "Signature",
  signature_desc: "Please sign below",
  signature_reminder_html:
    "<strong>Reminder:</strong> this form is a registration request to the Academy and does not constitute a definitive enrollment. You will receive a response within hours or days from management at the email address you provided.",
  label_date: "Date:",

  // Politique
  accept_policy_html:
    'I accept the <a href="/legal" class="underline text-rwdm-blue" target="_blank" rel="noopener noreferrer">privacy policy</a>.',

  // Bouton & cooldown
  button_submit: "Submit registration request",
  button_submit_loading: "Please wait...",
  cooldown_message: "You can resend a registration request in {{time}}",

  // Vérification orthographique
  spellcheck_title: "Registration information verification",
  spellcheck_title_2: "Verification of declaration information",
  spellcheck_field_player_last_name: "Player's last name",
  spellcheck_field_player_first_name: "Player's first name",
  spellcheck_field_parent1_last_name: "Primary guardian's last name",
  spellcheck_field_parent1_first_name: "Primary guardian's first name",
  spellcheck_field_parent1_email: "Primary guardian's email",
  spellcheck_field_parent2_last_name: "Secondary guardian's last name",
  spellcheck_field_parent2_first_name: "Secondary guardian's first name",
  spellcheck_field_parent2_email: "Secondary guardian's email",
  signature_placeholder: "Sign here",
  clear: "Clear",
  academy_info_html:
    'More information about our academies is available on the <a href="/about?tab=histoire#academies" class="underline text-rwdm-blue hover:text-rwdm-red transition-colors">About</a> page.',
  spellcheck_description:
    "Please review and confirm each field by ticking the checkbox.",
  spellcheck_not_provided: "Not provided",
  spellcheck_modify: "Modify",
  spellcheck_confirm_submit: "Confirm and submit",
  select_date_placeholder: "Select a date",
  toast_success_title: "Form Submitted",
  toast_success_description:
    "Your registration request has been sent successfully.",
  toast_error_title: "Error",
  toast_error_description: "An error occurred while sending the form.",
  toast_birthdate_missing_title: "Error",
  toast_birthdate_missing_desc: "Please select the player's birth date.",
  toast_age_invalid_title: "Invalid Age",
  toast_age_invalid_desc:
    "Player must be between 4 and 9 years old to register.",
  formType_registration: "registration",
  formType_selectionTests: "selection tests",
  formType_accidentReport: "accident report",
  formType_responsibilityWaiver: "liability waiver",

  form_submission_success: "Form {{formType}} submitted successfully!",
  form_submission_desc1:
    "Your request has been recorded and is being processed by our team.",
  form_submission_desc2:
    "You’ll receive a confirmation email and be kept up to date on any progress.",

  form_submission_warning_title: "Attention",
  form_submission_warning_text:
    "For security reasons, please wait at least 10 minutes before submitting another form.",

  return_home: "Back to home",
  // EN
  selection_tests_section_title: "Test information",
  selection_tests_section_subtitle:
    "Please select the category and the academy",

  selection_error_start_date_past_title: "Error",
  selection_error_start_date_past_desc: "The start date cannot be in the past.",
  selection_error_end_date_past_title: "Error",
  selection_error_end_date_past_desc: "The end date cannot be in the past.",
  selection_error_end_before_start_title: "Error",
  selection_error_end_before_start_desc:
    "The end date cannot be before the start date.",

  selection_player_section_title: "Player information",
  selection_player_section_subtitle:
    "Please fill out all the player's information",

  selection_label_category: "Category *",
  selection_placeholder_category: "Select a category",
  selection_label_academy: "Academy *",
  selection_placeholder_academy: "Select an academy",
  selection_label_last_name: "Last Name *",
  selection_label_first_name: "First Name *",
  selection_label_birth_date: "Birth Date *",
  selection_label_phone: "Player's phone (mobile)",
  selection_label_email: "Player's email",
  selection_label_current_club: "Player's current club",
  selection_tooltip_current_club:
    "If the player has no club, you can leave this blank.",
  selection_label_previous_club: "Player's previous club",
  selection_tooltip_previous_club:
    "If the player has never played for a club, you can leave this blank.",
  selection_label_position: "Position *",
  selection_placeholder_position: "Select a position",
  selection_position_default: "Field player (U5-U9)",

  selection_legal_section_title: "Legal guardian information",
  selection_legal_section_subtitle:
    "Please fill in the legal guardian's information for the player. Are you a player of legal age? You may select 'Legal representative'.",

  selection_label_parent_last_name: "Last Name *",
  selection_label_parent_first_name: "First Name *",
  selection_label_parent_phone: "Guardian's phone (mobile) *",
  selection_label_parent_email: "Guardian's email *",
  selection_label_parent_relation: "Relation *",
  selection_placeholder_parent_relation: "Select the relation",
  selection_option_parent: "Parent",
  selection_option_representative: "Legal representative",

  selection_signature_section_title: "Signature",
  selection_signature_section_subtitle:
    "Please sign to confirm your registration for the selection tests",
  selection_signature_info:
    "The Academy disclaims any liability for incidents, accidents, or thefts occurring on its premises or nearby. By signing this document, you acknowledge this information.",
  selection_signature_label:
    "Signature of the player or parents/legal guardian (for minors under 18)",
  selection_signature_placeholder:
    "Sign here to validate registration for the tests",

  selection_accept_policy_html:
    'I accept the <a href="/legal" class="underline text-rwdm-blue" target="_blank" rel="noopener noreferrer">privacy policy</a>.',

  selection_button_submit: "Submit test request",
  selection_button_cooldown: "Please wait ({{time}})",
  selection_cooldown_message: "You can submit another test request in {{time}}",

  selection_spellcheck_title: "Verification of test information",
  selection_spellcheck_field_player_last_name: "Player's last name",
  selection_spellcheck_field_player_first_name: "Player's first name",
  selection_spellcheck_field_player_email: "Player's email",
  selection_spellcheck_field_parent_last_name: "Parent's last name",
  selection_spellcheck_field_parent_first_name: "Parent's first name",
  selection_spellcheck_field_parent_email: "Parent's email",

  selection_error_birthdate_missing_title: "Error",
  selection_error_birthdate_missing_desc:
    "Please select the player's birth date.",
  selection_error_age_invalid_title: "Invalid age",
  selection_error_age_invalid_desc:
    "The player must be between 4 and 20 years old to take the technical test.",
  selection_error_academy_missing_title: "Error",
  selection_error_academy_missing_desc: "Please select an academy.",
  selection_success_submission_title: "Form submitted",
  selection_success_submission_description:
    "Your test request has been sent successfully.",
  selection_error_submission_title: "Error",
  selection_error_submission_description:
    "An error occurred while submitting the form.",
  category_U5: "U5",
  category_U6: "U6",
  category_U7: "U7",
  category_U8: "U8",
  category_U9: "U9",
  category_U10: "U10",
  category_U11: "U11",
  category_U12: "U12",
  category_U13: "U13",
  category_U14: "U14",
  category_U15_full: "U15 (available at RFE Academy)",
  category_U16: "U16",
  category_U17_full: "U17 (available at RFE Academy)",
  category_U18: "U18",
  category_U19_full: "U19 (available at RFE Academy)",
  category_U21: "U21",

  position_goalkeeper: "Goalkeeper",
  position_right_back: "Right back",
  position_left_back: "Left back",
  position_center_back: "Center back",
  position_defensive_mid: "Defensive midfielder",
  position_central_mid: "Central midfielder",
  position_attacking_mid: "Attacking midfielder",
  position_right_wing: "Right winger",
  position_left_wing: "Left winger",
  position_striker: "Striker",
  academy_RWDM_elite: "RWDM Academy (Elite)",
  academy_RFE_provincial: "RWDM ForEver Academy (Provincials)",
  selection_error_date_past_title: "Error",
  selection_error_date_past_desc: "Date cannot be in the past.",
  accident_info_alert_title: "Important",
  accident_info_alert_html: `
      Please submit your report within a maximum of <span class="text-red-500 font-semibold">19 days</span> after the accident. The nineteenth day may be refused. After this period, the request can no longer be processed.
      <br/><br/>
      The report is first validated by the club and then forwarded to the Belgian FA. Medical expenses are initially at your own charge.
      <br/><br/>
      At the end of your recovery, you must upload your healing certificate and your doctor's fees on this page. These documents will also be approved by the club before being sent to the Belgian FA for possible reimbursement.
      <br/><br/>
      <span class="font-semibold text-gray-700 dark:text-gray-300">
        Please also download the PDF below, have your doctor complete it, then attach it as a PDF when reporting the accident.
      </span>`,
  accident_section_title: "Accident information",
  accident_section_subtitle:
    "Please provide the basic information about the accident",
  label_accident_date: "Date of the accident *",
  tooltip_accident_date: "You cannot select a future date.",
  label_club_name: "Club name *",
  placeholder_category: "Select a category",
  label_player_first_name: "Player’s first name *",
  label_player_last_name: "Player’s last name *",
  label_email: "Email address *",
  label_phone: "Phone number *",
  label_accident_description: "Accident description *",
  placeholder_accident_description:
    "Describe how the accident happened, where, when, and the immediate consequences...",
  accident_description_counter: "{{count}}/700 characters",
  document_section_title: "Supporting document",
  document_section_subtitle:
    "Please choose the document type and upload a supporting PDF (medical report, etc.)",
  tabs_accident_report: "Accident report",
  tabs_healing_certificate: "Healing certificate",
  label_accident_code: "Report code",
  placeholder_accident_code: "Click ‘Generate’ to get a code",
  button_generate_code: "Generate",
  accident_code_info_html:
    'This code is essential to issue the healing certificate later. <span class="ml-1 font-medium text-red-500">Without this code</span>, you will not be able to submit a healing certificate linked to this report.',
  upload_click_to_upload:
    '<span class="font-semibold">Click to upload</span> or drag and drop',
  upload_guidance_pdf: "Up to {{max}} files (PDF, JPG, PNG – max. 10 MB each)",
  upload_guidance_single: "1 PDF file (MAX. 10MB)",
  button_remove_file: "Remove",
  checkbox_healing_sent: "I have already submitted an accident report",
  label_healing_code: "Report code received during the report *",
  placeholder_healing_code: "e.g.: XG72ZL",
  healing_code_valid:
    "Valid code! The report is successfully linked to the email: {{email}}",
  healing_code_invalid: "No report matches this code for the email.",
  healing_upload_prompt: "Please attach your healing certificate below:",
  signature_section_title: "Signature",
  signature_section_subtitle:
    "Please sign to confirm the accuracy of the information provided",
  signature_privacy_html: `
      For efficient handling of my case, and only for this purpose, I authorize the processing of my medical data related to the accident of which I was a victim, as described in the
      <a href="https://arena-nv.be/fr/products/4" class="text-blue-600 underline" target="_blank" rel="noopener noreferrer">
        Privacy Declaration</a>.
      In accordance with GDPR, I have the right of access, rectification, portability, objection, and erasure of my data (arena@arena-nv.be).`,
  signature_label_html:
    "<strong>Signature of the victim or parents/legal guardian (for children under 18 years)</strong>",
  signature_placeholder_decla: "Sign here to confirm the accident report",
  cooldown_message_html:
    "You can submit another report in <strong>{{time}}</strong>",
  spellcheck_field_email: "Email address",
  spellcheck_field_phone: "Phone number",
  label_academy: "Academy *",
  placeholder_select_academy: "Select an academy",
  not_provided: "Not provided",
  button_submit_accident: "Submit accident report",
  button_submit_accident_loading: "Please wait...",
  toast_too_many_files_title: "Too many files",
  toast_too_many_files_desc: "Maximum {{max}} file{{plural}} allowed.",
  toast_invalid_file_title: "Invalid file",
  toast_invalid_file_desc:
    "Only PDF, JPG, or PNG files under 10 MB are allowed.",
  toast_file_error_title: "File error",
  toast_file_error_healing_desc: "Please add at least one PDF file (max. 2).",
  toast_file_error_accident_desc:
    "Please add a PDF file for the accident report.",
  toast_invalid_code_title: "Invalid dossier code",
  toast_invalid_code_desc: "Please enter a valid existing report code.",
  toast_upload_error_title: "Upload error",
  toast_upload_error_desc: "An error occurred while uploading the file.",
  toast_upload_too_large_title: "File too large",
  toast_upload_too_large_desc: "Please select files under 10 MB each.",
  toast_submit_success_title: "Report submitted successfully",
  toast_submit_success_desc: "Your report has been sent.",
  toast_general_error_title: "Error",
  toast_general_error_desc: "An error occurred while sending the form.",
  document_label_accident: "Accident report",
  document_label_healing: "Healing certificate",
  medical_download_button: "Download medical form",
  medical_dialog_title: "Choose form language",
  medical_dialog_description: "The PDF form is available in French or Dutch.",
  medical_language_fr: "French",
  medical_language_nl: "Dutch",
  toast_download_title: "Download started",
  toast_download_desc_fr: "The French form is downloading.",
  toast_download_desc_nl: "The Dutch form is downloading.",
  date_invalid_title: "Invalid date",
  date_invalid_desc: "You cannot report an accident in the future.",
  declaration_refused_title: "Report refused",
  declaration_refused_desc:
    "Your report can no longer be accepted because the accident occurred more than 19 days ago.",
  declaration_valid_title: "Report valid",
  declaration_valid_desc: "Your accident report meets the 19-day deadline.",
  toast_generate_code_title: "Code generated successfully",
  toast_generate_code_desc:
    "Keep this code safe so you can link your healing certificate later.",
  parse_data_error: "Unable to parse data for request ID {{id}}",
  check_code_general_error: "Error checking code validity",
  waiver_player_info_title: "Player information",
  waiver_player_info_subtitle: "Please fill out the player's information",
  label_player_birth_date: "Birth date *",

  waiver_parent_info_title: "Parent/guardian information",
  waiver_parent_info_subtitle:
    "Please fill in your information as the legal guardian. Are you a player and over 18? You may enter your own data.",
  waiver_waiver_title: "Liability waiver",
  waiver_waiver_subtitle: "Please read carefully before signing",

  waiver_date_confirmation_title: "Date and confirmation",
  waiver_date_confirmation_subtitle:
    "Please confirm the date and enter 'Read and approved'",
  label_waiver_date: "Signature date",
  label_approval_text: 'Mention "Read and approved"',
  placeholder_approval_text: "Select your agreement",
  option_approval_text: "Read and approved",

  signature_placeholder_waiver: "Sign here to validate the liability waiver",

  button_submit_waiver: "Submit waiver",
  cooldown_message_waiver_html:
    "You can submit the liability waiver again in <strong>{{time}}</strong>",

  spellcheck_title_waiver: "Verification of waiver information",
  spellcheck_field_parent_first_name: "Guardian’s first name",
  spellcheck_field_parent_last_name: "Guardian’s last name",
  spellcheck_field_parent_email: "Guardian’s email",

  toast_error_description_required: "Please fill out all required fields.",
  toast_success_waiver_title: "Waiver submitted successfully",
  toast_success_waiver_description: "Your liability waiver has been sent.",
  toast_error_generic_description: "An error occurred while sending the form.",
  toast_error_upload_signature: "Error uploading the signature.",
  toast_error_api: "API error.",
  waiver_text_template:
    "I, {{parentFirstName}} {{parentLastName}}, legal guardian of the player {{playerFirstName}} {{playerLastName}}, born on {{playerBirthDate}}, and affiliated with club {{currentClub}}, hereby release RWDM Academy from any liability for accidents that may occur during training sessions and/or friendly matches in which the player participates from this day forward.",
  tab_confidentiality: "Privacy Policy",
  tab_terms: "Terms of Use",
  tab_legal: "Legal Notice",
  tab_cookies: "Cookies",
  btn_back_home: "Back to Home",
  page_legal_title: "Legal Information",
  confidentiality_title: "Privacy Policy",
  confidentiality_last_updated: "Last updated:",
  confidentiality_section1_title: "1. Introduction",
  confidentiality_section1_text:
    "Welcome to the RWDM Academy platform. We are committed to protecting the privacy and personal data of our service users. This privacy policy explains how we collect, use, share, and safeguard your personal information.",
  confidentiality_section2_title: "2. Data Collected",
  confidentiality_section2_intro:
    "We collect the following data during your use:",
  confidentiality_li_name: "Name, first name, date and place of birth",
  confidentiality_li_contact:
    "Address, postal code, city, email, phone (mobile)",
  confidentiality_li_sport: "Registration season, academy, category, position",
  confidentiality_li_club: "Current and previous club",
  confidentiality_li_responsible:
    "Type of guardian (father/mother/guardian), name, first name, phone, email, address",
  confidentiality_li_consent:
    "Image consent and signature (date, “Read and approved”)",
  confidentiality_li_accident:
    "Date and description of the accident, dossier code, PDF supporting document",
  confidentiality_li_navigation: "Navigation data (stored in localStorage)",
  confidentiality_li_minors:
    "Minors under 18 are not allowed to complete these forms.",
  confidentiality_section3_title: "3. Use of Data",
  confidentiality_section3_li1:
    "Manage your requests (registration, test, accident, waiver)",
  confidentiality_section3_li2: "Contact you for appointments and follow‑up",
  confidentiality_section3_li3: "Improve our services and platform security",
  confidentiality_section4_title: "4. Legal Basis for Processing",
  confidentiality_section4_li1: "Explicit consent",
  confidentiality_section4_li2: "Contract performance",
  confidentiality_section4_li3: "Legitimate interest",
  confidentiality_section4_li4: "Legal obligations",
  confidentiality_section5_title: "5. Data Sharing",
  confidentiality_section5_li1: "URBSFA for official registrations",
  confidentiality_section5_li2: "IT service providers",
  confidentiality_section5_li3: "Competent authorities when required by law",
  confidentiality_section5_text:
    "We never sell your personal data to third parties.",
  confidentiality_section6_title: "6. Retention Period",
  confidentiality_section6_li1:
    "Duration of request processing and associated follow‑up",
  confidentiality_section6_li2: "Statutory retention periods",
  confidentiality_section6_li3: "Up to 3 years after last activity",
  confidentiality_section7_title: "7. Your Rights",
  confidentiality_section7_li1: "Right of access, rectification, erasure",
  confidentiality_section7_li2: "Right to restriction and portability",
  confidentiality_section7_li3: "Right to object and withdraw consent",
  confidentiality_section7_contact: "To exercise these rights, contact",
  confidentiality_section8_title: "8. Data Security",
  confidentiality_section8_text:
    "We implement technical and organizational measures to protect your data against loss, unauthorized access, and disclosure.",
  confidentiality_section9_title: "9. International Transfers",
  confidentiality_section9_text:
    "Data is stored and processed within the European Union. Any transfer outside the EU is covered by GDPR‑compliant safeguards.",
  confidentiality_section10_title: "10. Contact",
  confidentiality_section10_text: "For any questions, write to",
  last_updated: "Last updated",
  confidentiality_section3_intro: "We use your data to:",
  confidentiality_section3_text:
    "We use your data to process your requests (registration, selection tests, accident report, waiver), contact you for appointments and follow‑up, improve our services and platform security.",
  cgu_title: "Terms of Use",
  cgu_section1_title: "1. Acceptance of Terms",
  cgu_section1_text:
    "By submitting requests via the RWDM Academy platform, you agree to be bound by these Terms of Use. If you do not agree, please do not use our service.",
  cgu_section2_title: "2. Service Description",
  cgu_section2_text1:
    "The RWDM Academy platform allows you to submit requests for:",
  cgu_section2_li1: "academy registration request",
  cgu_section2_li2: "selection test request",
  cgu_section2_li3: "accident report",
  cgu_section2_li4: "liability waiver signature",
  cgu_section2_text2:
    "You will receive an automatic acknowledgement by email, followed by a confirmation (acceptance, appointment, next steps) by email.",
  cgu_section3_title: "3. Access and Submission Requirements",
  cgu_section3_text1: "To submit a request you must:",
  cgu_section3_li1:
    "Be at least 18 years old or, if a minor, be represented by a parent/guardian",
  cgu_section3_li2: "Provide accurate, complete and up‑to‑date information",
  cgu_section3_li3: "Comply with all applicable laws",
  cgu_section4_title: "4. Administrative Account Management",
  cgu_section4_text:
    "Only owner, superadmin and admin accounts are created manually by the platform owner. End users have no account creation functionality.",
  cgu_section5_title: "5. Acceptable Use",
  cgu_section5_text1: "You agree not to:",
  cgu_section5_li1: "Damage or disable the service",
  cgu_section5_li2: "Submit false or misleading information",
  cgu_section5_li3: "Attempt to access other users’ requests or accounts",
  cgu_section5_li4: "Use unauthorized automated means",
  cgu_section5_li5: "Bypass security measures",
  cgu_section6_title: "6. Intellectual Property",
  cgu_section6_text:
    "All content (logos, texts, images) is protected. Any reproduction without written permission is prohibited.",
  cgu_section7_title: "7. Liability",
  cgu_section7_text:
    "The service is provided “as is” and “as available.” We do not guarantee continuous availability and are not liable for indirect damages.",
  cgu_section8_title: "8. Changes to Terms",
  cgu_section8_text:
    "We may modify these terms at any time. Changes take effect upon posting; continued use constitutes acceptance.",
  cgu_section9_title: "9. Termination",
  cgu_section9_text:
    "We may suspend or terminate access for violations. You may request deletion of your request data at any time.",
  cgu_section10_title: "10. Governing Law and Jurisdiction",
  cgu_section10_text:
    "These terms are governed by Belgian law. Any dispute will be subject to the courts of Brussels.",
  cgu_section11_title: "11. Contact",
  cgu_section11_text:
    "For any questions, contact: RWDM Academy, Rue Charles Malis 61, 1080 Molenbeek‑Saint‑Jean, {{email}}",
  cgu_section2_intro:
    "The RWDM Academy platform allows you to submit requests for:",
  cgu_section2_item1: "academy enrollment request",
  cgu_section2_item2: "selection test request",
  cgu_section2_item3: "accident report",
  cgu_section2_item4: "liability waiver signing",
  cgu_section2_text:
    "You will receive an automatic acknowledgment by email, followed by a confirmation (acceptance, appointment, next steps) by email.",
  cgu_section3_intro: "To submit a request, you must:",
  cgu_section3_item1:
    "Be at least 18 years old or, if a minor, represented by a parent/guardian",
  cgu_section3_item2: "Provide accurate, complete and up‑to‑date information",
  cgu_section3_item3: "Comply with all applicable laws",
  cgu_section5_intro: "You agree not to:",
  cgu_section5_item1: "Damage or disable the service",
  cgu_section5_item2: "Submit false or misleading information",
  cgu_section5_item3: "Attempt to access other users’ requests or accounts",
  cgu_section5_item4: "Use unauthorized automated means",
  cgu_section5_item5: "Bypass security measures",
  cgu_section11_contact_intro: "For any questions, please contact:",
  // Section 1
  legal_section1_title: "1. Legal information",
  legal_section1_intro: "This platform is published by:",
  legal_section1_name_label: "Name",
  legal_section1_address_label: "Address",
  legal_section1_country_label: "Country",
  legal_section1_email_label: "Email",

  // Section 2
  legal_section2_title: "2. Publication responsible",
  legal_section2_text:
    "The publication responsible is Nawfel Ajari, software engineer at <a href='https://www.nainnovations.be' target='_blank' rel='noopener noreferrer' style='text-decoration: underline; color: #6b7280;' onmouseover='this.style.color=\"#4b5563\"' onmouseout='this.style.color=\"#6b7280\"'>NA Innovations</a>.",

  legal_section2_subtitle: "Technical development",
  legal_section2_dev_text: "The site was developed by Nawfel Ajari.",

  // Section 3
  legal_section3_title: "3. Hosting",
  legal_section3_intro: "This platform is hosted by:",
  legal_section3_provider: "Hostinger",
  legal_section3_address:
    "Address: Hostinger International Ltd, 61 Lordou Vironos Street, 6023 Larnaca, Cyprus",
  legal_section3_website: "Website: https://www.hostinger.com",

  // Section 4
  legal_section4_title: "4. Intellectual property",
  legal_section4_text:
    "All content (texts, images, logos, etc.) is the exclusive property of RWDM Academy or its partners. Any reproduction or adaptation without prior written permission is prohibited.",

  // Section 5
  legal_section5_title: "5. Hyperlinks",
  legal_section5_text:
    "The platform may contain links to other sites. We have no control over their content and disclaim all liability.",

  // Section 6
  legal_section6_title: "6. Liability",
  legal_section6_text:
    "We strive for accuracy of information. However, we do not guarantee completeness or correctness and disclaim all liability for omissions or inaccuracies.",

  // Section 7
  legal_section7_title: "7. Applicable law and jurisdiction",
  legal_section7_text:
    "These legal notices are governed by Belgian law. In case of dispute, only the courts of Brussels have jurisdiction.",
  cookie_policy_title: "Cookie Policy",
  cookie_policy_last_updated: "Last updated",
  cookie_section1_title: "1. No HTTP cookies",
  cookie_section1_text:
    "We do not use any HTTP cookies. All preferences (language, display) are stored in client‑side localStorage.",
  cookie_section2_title: "2. Why no cookies?",
  cookie_section2_text: "By storing preferences in localStorage, we:",
  cookie_section2_point1: "Reduce HTTP overhead (no cookie headers)",
  cookie_section2_point2: "Keep data longer without automatic expiration",
  cookie_section2_point3: "Avoid size and parsing constraints of cookies",
  cookie_section3_title: "3. Managing local storage",
  cookie_section3_text:
    "You can clear or disable localStorage via your browser tools; this will reset your preferences (language, theme, etc.).",
  cookie_section4_title: "4. Functional impact",
  cookie_section4_text:
    "Removing data from localStorage may cause your language and settings to revert to defaults on each visit.",
  cookie_section5_title: "5. Contact",
  cookie_section5_text:
    "For any questions about this policy, please contact {email}.",
  cookie_section2_li1: "Reduce HTTP requests (no cookie headers)",
  cookie_section2_li2: "Keep data longer without automatic expiration",
  cookie_section2_li3: "Avoid size‑ and parsing‑limitations of cookies",
  maintenance_title: "Forms under maintenance",
  maintenance_message:
    "Our form is unavailable due to maintenance by our team. You can still contact us using our contact form:",

  thanks_patience: "We’ll be back soon. Thank you for your patience!",
  account_button: "My Account",
  logout_title: "Logout",
  logout_message: "Are you sure you want to log out?",
  confirm_action_title: "Confirm Action",
  send_email_checkbox_label: "Send confirmation email",
  confirm: "Confirm",
  account: "Account",
  error: "Error",
  success: "Success",
  passwords_do_not_match: "Passwords do not match.",
  password_update_success: "Password updated successfully.",
  password_update_error: "Error updating password.",
  server_error_password_update: "Server error while updating password.",
  change_password: "Change Password",
  enter_new_password: "Enter your new password and confirm it",
  new_password: "New Password",
  confirm_password: "Confirm Password",
  update: "Update",
  assignments: "Assignments",
  created_on: "Created on",
  close: "Close",
  function_label: "Function",
  role_owner: "Owner",
  role_superadmin: "Superadmin",
  role_admin: "Admin",
  role_user: "User",
  dashboard_title: "Dashboard",
  dashboard_description: "Manage requests and track their progress",
  dashboard_view_planning: "View planning",
  requests: "Requests",
  stats: "Statistics",
  card_requests_title: "List of requests",
  card_requests_info:
    "Rejected requests are permanently deleted from the database after 24 hours.",
  card_requests_assigned_label: "My assignments",
  toast_appointment_title: "Appointment Scheduled",
  toast_appointment_desc_prefix: "An appointment was added for",
  toast_appointment_desc_suffix: ".",
  toast_request_deleted_title: "Request deleted",
  toast_request_deleted_description:
    "The request has been permanently deleted.",
  toast_request_auto_deleted_title: "Request automatically deleted",
  toast_request_auto_deleted_description:
    "Request {{id}} was deleted after 24h.",
  toast_assign_error_title: "Error",
  toast_assign_error_description: "Unable to assign the request.",
  toast_status_updated_title: "Status updated",
  toast_status_updated_description:
    'The status has been changed to "{{status}}".',
  toast_status_error_title: "Error",
  toast_status_error_description: "Unable to change the status.",
  toast_accident_sent_title: "Declaration sent",
  toast_accident_sent_description: "The accident report has been submitted.",
  toast_accident_error_title: "Error",
  toast_accident_error_description: "Error while sending the accident report.",
  toast_certificate_sent_title: "Certificate sent",
  toast_certificate_sent_description:
    "Both documents have been submitted and marked as completed.",
  toast_certificate_error_title: "Error",
  toast_certificate_error_description: "Error while sending the certificate.",
  search_filters_title: "Search filters",
  search_input_placeholder: "Search by name, email or ID...",
  select_all_admins: "All admins",
  select_unassigned: "Unassigned",
  select_status_placeholder: "Status",
  select_all_statuses: "All statuses",
  status_new: "New",
  status_assigned: "Assigned",
  status_in_progress: "In progress",
  status_completed: "Completed",
  status_rejected: "Rejected",
  select_all_types: "All types",
  form_type_registration: "Registration",
  form_type_selection_tests: "Selection tests",
  form_type_accident_report: "Accident",
  form_type_responsibility_waiver: "Waiver",
  table_id: "ID",
  table_type: "Type",
  table_name: "Name",
  table_status: "Status",
  table_assigned_to: "Assigned to",
  table_date: "Date",
  table_appointment: "Appointment",
  table_actions: "Actions",
  table_no_results: "No request matches your filters.",
  toast_assign_inactive_title: "Assignment error",
  toast_assign_inactive_description: "You cannot assign an inactive user.",
  label_inactive: "(inactive)",
  dropdown_view_request: "View request",
  dropdown_set_in_progress: "Mark as in progress",
  dropdown_appointment: "Appointment",
  toast_assign_required_title: "Assignment required",
  toast_accept_assign_required_desc:
    "An administrator must be assigned before accepting.",
  toast_reject_assign_required_desc:
    "Please assign an administrator before rejecting.",
  pagination_page_prefix: "Page ",
  pagination_page_separator: " of ",
  button_actions_title: "Actions",
  badge_status_new: "New",
  badge_status_assigned: "Assigned",
  badge_status_in_progress: "In progress",
  badge_status_completed: "Completed",
  badge_status_rejected: "Rejected",
  badge_status_unknown: "Unknown",
  pending_accidents_title: "Pending accident reports",
  pending_accidents_info:
    "Accident reports are held here while waiting for the respective healing certificate.",
  valid_accidents_label: "Valid accident reports",
  dialog_edit_federation_email_title: "Edit Belgian Federation email",
  button_save: "Save",
  placeholder_new_recipient: "New recipient",
  table_header_id: "ID",
  table_header_accident_date: "Accident date",
  table_header_name: "Name",
  table_header_status: "Status",
  table_header_assigned_to: "Assigned to",
  table_header_deadline: "Deadline",
  table_header_actions: "Actions",
  table_header_recipients: "Recipients",
  badge_label_in_progress: "In progress",
  healing_certificate_received: "Healing certificate received",
  pagination_prefix: "Page ",
  pagination_separator: " of ",
  confirm_send_declaration_title: "Send to Belgian Federation",
  confirm_send_declaration_message:
    "Are you sure you want to send this accident report to the Belgian Football Federation?",
  confirm_send_healing_title: "Send healing certificate",
  confirm_send_healing_message:
    "Are you sure you want to send this healing certificate to the Belgian Federation?",
  completed_requests_title_prefix: "Recently completed requests (",
  completed_requests_title_separator: " displayed out of ",
  completed_requests_title_suffix: ")",
  no_completed_requests: "No completed requests at the moment.",
  table_header_type: "Type",
  table_header_date: "Date",
  button_view_completed_prefix: "View ",
  button_view_completed_suffix: " completed requests",
  card_requests_stats_title: "Request statistics",
  label_new_requests: "New requests",
  label_requests_in_progress: "Requests in progress",
  label_completed_requests: "Completed requests",
  label_pending_accidents: "Pending accidents",
  card_requests_evolution_title: "Request trends over the year",
  chart_title_requests_by_type: "Requests by type over the year",
  members_title: "Members",
  members_subtitle: "Manage the academy members",
  planning_title: "Planning",
  planning_description: "View and manage appointments at the front desk",
  add_appointment: "Add appointment",
  view_day: "Day view",
  view_week: "Week view",
  all_admins: "All admins",
  schedule_new_appointment: "Schedule a new appointment",
  appointment_date_label: "Appointment date",
  appointment_time_label: "Appointment time",
  appointment_type_label: "Appointment type",
  type_registration: "Academy registration",
  type_selection_tests: "Selection tests",
  type_accident_report: "Accident report",
  type_responsibility_waiver: "Responsibility waiver",
  type_other: "Other",
  person_name_label: "Person’s name",
  person_name_placeholder: "Enter full name",
  contact_email_label: "Contact email",
  contact_email_placeholder: "example@email.com",
  select_time_placeholder: "Select a time",
  assigned_admin_label: "Assigned administrator",
  select_admin_placeholder: "Select an administrator",
  no_admins_found: "No administrator found",
  notes_label: "Notes (optional)",
  notes_placeholder: "Add additional notes",
  cancel_button: "Cancel",
  schedule_appointment_button: "Schedule appointment",
  appointment_details_title: "Appointment details",
  appointment_detail_client: "Client:",
  appointment_detail_email: "Email:",
  appointment_detail_date: "Date:",
  appointment_detail_time: "Time:",
  appointment_detail_type: "Type:",
  appointment_detail_admin: "Administrator:",
  appointment_detail_notes: "Notes:",
  appointment_no_notes: "No notes",
  close_button: "Close",
  calendar_title: "Calendar",
  legend_title: "Legend",
  legend_with_appointments: "Day with appointments",
  legend_selected_day: "Selected day",
  appointments_on: "Appointments on",
  no_appointments: "No appointments for this date.",
  add_appointment_on_date: "Add an appointment on this date",
  registration_label: "Registration",
  selection_tests_label: "Tests",
  accident_report_label: "Accident",
  responsibility_waiver_label: "Waiver",
  other_label: "Other",
  admin_label: "Administrator:",
  no_admin_assigned: "No administrator assigned",
  no_notes: "No notes",
  day_selected: "selected day",
  legend_registration: "Academy Registration",
  legend_selection_tests: "Selection Tests",
  legend_accident_report: "Accident Report",
  legend_responsibility_waiver: "Responsibility Waiver",
  legend_other: "Other",
  week_title_prefix: "Week of",
  week_title_middle: "to",
  button_today: "Today",
  table_header_time: "Time",
  label_available: "Available",
  label_client: "Client",
  filter_applied_title: "Filter applied",
  filter_applied_desc: "Your schedule now shows only appointments of",
  filter_cleared_title: "Filter cleared",
  page_docs_title: "Document Management",
  page_docs_desc: "Browse members’ documents here",
  button_create_request: "Create a request",
  completedRequests: "Completed Requests",
  statistics: "Statistics",
  documents: "Documents",
  noDocumentsMatch: "No documents match your criteria.",
  generatePdfTitle: "Generate PDF",
  generatePdfMessage:
    "Are you sure you want to generate the PDF for this request?",
  revertToInProgressTitle: "Revert to In Progress",
  revertToInProgressMessage:
    "Are you sure you want to move this request to 'In Progress' status?",
  searchFilters: "Search Filters",
  searchPlaceholder: "Search by name, first name, email or phone…",
  allAdmins: "All admins",
  allTypes: "All types",
  registration: "Registrations",
  selectionTests: "Technical tests",
  responsibilityWaiver: "Liability waivers",
  accidentReport: "Accident reports",
  tableHeaderID: "ID",
  tableHeaderType: "Type",
  tableHeaderName: "Name",
  tableHeaderEmail: "Email",
  tableHeaderStatus: "Status",
  tableHeaderAssignedTo: "Assigned to",
  tableHeaderDate: "Date",
  tableHeaderActions: "Actions",
  completed: "Completed",
  viewDetails: "View details",
  edit: "Edit",
  setInProgress: "Set in progress",
  generatePDF: "Generate PDF",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  create_member: "Create member",
  all_members: "All members",
  old_members: "Former members",
  roles_legend_title: "Roles Legend",
  role_owner_desc: "Platform director – full access to all features.",
  role_superadmin_desc:
    "Management lead – access to configuration, users, and assignments.",
  role_admin_desc: "Schedule manager – access to the calendar and dashboard.",
  members_registered: "Registered members",
  table_header_avatar: "Avatar",
  table_header_full_name: "Full name",
  table_header_email: "Email",
  table_header_function: "Function",
  table_header_role: "Role",
  table_header_created_at: "Created at",
  no_member_found: "No member found",
  page_info: "Page",
  table_header_assignments: "Assignments",
  table_header_deleted_at: "Deleted at",
  "button.restore_member": "Restore",
  reactivateModalTitle: "Reactivate account",
  reactivateModalConfirmStart:
    "Are you sure you want to reactivate the account of",
  reactivateModalConfirmEnd: " ?",
  buttonCancel: "Cancel",
  buttonConfirm: "Confirm",
  deleteMemberTitle: "Delete permanently",
  deleteMemberMessage:
    "Are you sure you want to delete this member permanently? This action cannot be undone and will leave assignments without an owner.",
  noOldMembers: "No old member found",
  "pagination.page": "Page",
  "pagination.of": "of",
  createMember: "Create a member",
  firstNamePlaceholder: "First name",
  lastNamePlaceholder: "Last name",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  functionPlaceholder: "Role / Position",
  roleLabel: "Role:",
  "button.create_member": "Create member",
  "member.edit_title": "Edit member",
  "member.edit_password_placeholder": "Leave empty to keep unchanged",
  "button.save": "Save",
  "deleteMember.title": "Delete Member",
  "deleteMember.prompt": "Are you sure you want to delete this member",
  "button.cancel": "Cancel",
  "button.delete": "Delete",
  "chart.completedByMonth.title": "Requests completed per month and per admin",
  "chart.byAdminAndMonth.subtitle": "By admin and by month",
  "dialog.editRequest.titlePrefix": "Edit request #",
  clubName: "Club",
  playerLastName: "Player last name",
  playerFirstName: "Player first name",
  email: "Email",
  phone: "Phone",
  accidentDate: "Accident date",
  description: "Description",
  filePaths: "Supporting documents",
  category: "Category",
  codeDossier: "Case code",
  documentLabel: "Document type",
  parentLastName: "Parent last name",
  parentFirstName: "Parent first name",
  parentPhone: "Parent phone",
  parentEmail: "Parent email",
  playerBirthDate: "Player birth date",
  currentClub: "Current club",
  previousClub: "Previous club",
  signatureDate: "Signature date",
  approvalText: "Approval text",
  filePath: "File path",
  season: "Registration season",
  academy: "Academy",
  lastName: "Last name",
  firstName: "First name",
  birthDate: "Birth date",
  birthPlace: "Birth place",
  address: "Address",
  postalCode: "Postal code",
  city: "City",
  position: "Position",
  parentRelation: "Relation",
  parent1Type: "Parent 1 relationship",
  parent1LastName: "Parent 1 last name",
  parent1FirstName: "Parent 1 first name",
  parent1Phone: "Parent 1 phone",
  parent1Email: "Parent 1 email",
  parent1Address: "Parent 1 address",
  parent1PostalCode: "Parent 1 postal code",
  parent1Gsm: "Parent 1 mobile",
  parent2Type: "Parent 2 relationship",
  parent2LastName: "Parent 2 last name",
  parent2FirstName: "Parent 2 first name",
  parent2Phone: "Parent 2 phone",
  parent2Email: "Parent 2 email",
  parent2Address: "Parent 2 address",
  parent2PostalCode: "Parent 2 postal code",
  parent2Gsm: "Parent 2 mobile",
  imageConsent: "Image consent",
  createdAt: "Creation date",
  save: "Save",
  enterClubName: "Enter Club",
  enterPlayerLastName: "Enter Player’s Last Name",
  enterPlayerFirstName: "Enter Player’s First Name",
  enterEmail: "Enter Email",
  enterPhone: "Enter Phone",
  enterAccidentDate: "Select the accident date",
  enterDescription: "Enter the description",
  enterFilePaths: "Add supporting documents",
  enterSignature: "Provide signature",
  enterCategory: "Enter the category",
  enterCodeDossier: "Enter the case code",
  enterDocumentLabel: "Enter the document type",
  enterParentLastName: "Enter the parent’s last name",
  enterParentFirstName: "Enter the parent’s first name",
  enterParentPhone: "Enter the parent’s phone",
  enterParentEmail: "Enter the parent’s email",
  enterPlayerBirthDate: "Select the player’s birth date",
  enterCurrentClub: "Enter the current club",
  enterPreviousClub: "Enter the previous club",
  enterSignatureDate: "Select the signature date",
  enterApprovalText: "Enter the approval text",
  enterFilePath: "Enter the file path",
  enterSeason: "Enter the season",
  enterAcademy: "Enter the academy",
  enterLastName: "Enter the player’s last name",
  enterFirstName: "Enter the player’s first name",
  enterBirthDate: "Select the birth date",
  enterBirthPlace: "Enter the birth place",
  enterAddress: "Enter the address",
  enterPostalCode: "Enter the postal code",
  enterCity: "Enter the city",
  enterPosition: "Enter the position",
  enterParentRelation: "Enter the parent relation",
  enterParent1Type: "Enter parent 1 relationship",
  enterParent1LastName: "Enter parent 1 last name",
  enterParent1FirstName: "Enter parent 1 first name",
  enterParent1Phone: "Enter parent 1 phone",
  enterParent1Email: "Enter parent 1 email",
  enterParent1Address: "Enter parent 1 address",
  enterParent1PostalCode: "Enter parent 1 postal code",
  enterParent1Gsm: "Enter parent 1 mobile",
  enterParent2Type: "Enter parent 2 relationship",
  enterParent2LastName: "Enter parent 2 last name",
  enterParent2FirstName: "Enter parent 2 first name",
  enterParent2Phone: "Enter parent 2 phone",
  enterParent2Email: "Enter parent 2 email",
  enterParent2Address: "Enter parent 2 address",
  enterParent2PostalCode: "Enter parent 2 postal code",
  enterParent2Gsm: "Enter parent 2 mobile",
  enterImageConsent: "Enter image consent",
  enterCreatedAt: "Select the creation date",
  "toast.error": "Error",
  "toast.emptyDetails": "Details cannot be empty.",
  "toast.updated": "Updated",
  "toast.updatedDesc": "Data has been successfully updated.",
  "toast.saveFailed": "Failed to save.",
  "dialog.editRequest.title": "Edit Request",
  "appointmentDialog.title": "Choose appointment type",
  "appointmentDialog.description":
    "Please select the appointment type for the player.",
  "appointment.scheduleTest": "Schedule a skills test",
  "appointment.visitOffice": "Appointment at the office",
  "settings.title": "Site Settings",
  "settings.description":
    "Customize the client-side platform and manage maintenance",
  "language.fr": "French",
  "language.nl": "Dutch",
  "language.en": "English",
  "maintenance.enable": "Enable maintenance",
  "maintenance.disable": "Disable maintenance",
  "maintenance.toggling": "…",
  "maintenance.warning.title": "Warning",
  "maintenance.warning.content":
    "When a term is changed in one language, remember to update it in all other languages to ensure",
  "maintenance.warning.highlight": "consistency",
  "maintenance.warning.content2":
    ". When maintenance mode is enabled, all visitors are redirected to a maintenance view instead of the forms.",
  "tabs.general": "General",
  "tabs.about": "About",
  "tabs.contact": "Contact",
  "button.saveChanges": "Save changes",
  "confirmation.saveSettings": "Are you sure you want to save these settings?",
  "confirmation.updatedTranslations": "I have updated all translations.",
  "maintenance.confirmEnable": "Confirm enable",
  "maintenance.confirmDisable": "Confirm disable",
  "maintenance.confirmEnableMessage":
    "Are you sure you want to enable maintenance mode?",
  "maintenance.confirmDisableMessage":
    "Are you sure you want to exit maintenance mode?",
  "settings.confirmSaveTitle": "Confirm save",
  "siteIdentity.title": "Site identity",
  "siteIdentity.description": "Choose your club’s official colors.",
  "siteIdentity.unavailable": "Not available right now",
  "siteIdentity.color1Label": "Site color 1",
  "siteIdentity.color2Label": "Site color 2",
  "siteIdentity.logoLabel": "Logo (file)",
  "toasts.logoUploaded": "Logo uploaded successfully!",
  "clubDetails.clubName": "Club Name",
  "clubDetails.contactTitle": "Club Contact",
  "clubDetails.contactDesc": "Fill in the address and location information.",
  "clubDetails.address": "Club Address",
  "clubDetails.postalCode": "Postal Code",
  "clubDetails.commune": "Municipality",
  "clubDetails.country": "Country",
  "contactSocial.title": "Contact & Social Media",
  "contactSocial.description":
    "This information is displayed publicly on the site.",
  "contactForm.email": "Email",
  "contactForm.facebookUrl": "Facebook URL",
  "contactForm.instagramUrl": "Instagram URL",
  language_changed_title: "Language changed",
  language_changed_desc: "The interface language has been updated.",
  "clubStats.title": "Club Statistics",
  "clubStats.description":
    "These figures reflect the club’s impact and history.",
  "clubAbout.title": "About the Club",
  "clubAbout.description":
    "Fill in the key information that presents the club’s history, mission, and approach.",
  tabsHistory: "History",
  tabsMission: "Mission",
  tabsApproach: "Approach",
  labelDescription: "Description",
  photoHistoryFile: "History Photo (file)",
  photoMissionFile: "Mission Photo (file)",
  photoApproachFile: "Approach Photo (file)",
  maxSize: "Maximum size: 2 MB",
  "academies.title": "Our Academies",
  "academies.description":
    "Enter the name, description, and an image for each academy.",
  "academies.tab1": "Academy 1",
  "academies.tab2": "Academy 2",
  "academies.tab3": "Academy 3",
  "academies.name1": "Academy 1 Name",
  "academies.name2": "Academy 2 Name",
  "academies.name3": "Academy 3 Name",
  "academies.desc1": "Academy 1 Description",
  "academies.desc2": "Academy 2 Description",
  "academies.desc3": "Academy 3 Description",
  "academies.photo1": "Academy 1 Photo (file)",
  "academies.photo2": "Academy 2 Photo (file)",
  "academies.photo3": "Academy 3 Photo (file)",
  "academies.photoLabel": "Academy photo",
  academiesName1: "Academy name",
  academiesDesc1: "Academy description",
  academiesUploadSuccess1: "Image for Academy uploaded successfully!",
  academiesName2: "Academy name",
  academiesDesc2: "Academy description",
  academiesUploadSuccess2: "Image for Academy uploaded successfully!",
  academiesName3: "Academy name",
  academiesDesc3: "Academy description",
  academiesUploadSuccess3: "Image for Academy uploaded successfully!",
  valuesTitle: "Our values",
  valuesDescription:
    "The club is committed to instilling strong values such as respect, fair play and team spirit.",
  value1Title: "Value 1 Title",
  value1TitlePlaceholder: "e.g. Respect, Fair-play…",
  value1Description: "Value 1 Description",
  value1DescriptionPlaceholder: "Describe what this value means for the club",

  value2Title: "Value 2 Title",
  value2TitlePlaceholder: "e.g. Solidarity, Team spirit…",
  value2Description: "Value 2 Description",
  value2DescriptionPlaceholder: "Explain why this value is important",

  value3Title: "Value 3 Title",
  value3TitlePlaceholder: "e.g. Responsibility, Commitment…",
  value3Description: "Value 3 Description",
  value3DescriptionPlaceholder: "Detail this value for your members",
  openingHoursTitle: "Opening Hours",
  openingHoursDescription:
    "If both opening and closing times are 00:00, the day is considered closed.",
  statusOpen: "Open",
  statusClosed: "Closed",
  "companyInfo.title": "Company Information",
  "companyInfo.description":
    "These details will be publicly displayed on the Contact page of the site.",
  "companyInfo.accountName": "Account Name",
  "companyInfo.vatNumber": "VAT Number",
  "companyInfo.companyNumber": "Company Number",
  statistics_title: "Statistics",
  statistics_description: "Financial management & academy pyramid hierarchy",
  financialManagement: "Financial Management",
  hierarchy: "Hierarchy",
  apiActive: "API active",
  apiUnavailable: "API unavailable",
  hierarchyTitle: "Teams Hierarchy",
  hierarchyDesc1: "Data provided by the API",
  hierarchyDesc2: "in real time. Some names may appear duplicated.",
  "filters.title": "Search Filters",
  "filters.searchPlayer": "Search a player…",
  "filters.allCategories": "All categories",
  "invoices.byCategoryTitle": "Invoices by category",
  byCategory: "By category",
  paymentsTrend: "Payment trend",
  paid: "Paid",
  unpaid: "Unpaid",
  invoiceList: "Invoice List",
  "invoiceList.date": "Invoice Date",
  "invoiceList.number": "Number",
  "invoiceList.fullName": "Full Name",
  "invoiceList.totalAmount": "Total Amount",
  "invoiceList.paidAmount": "Paid Amount",
  "invoiceList.team": "Team",
  "categoryCounts.title": "Category Statistics",
  "categoryCounts.teamsSingular": "team",
  "categoryCounts.teamsPlural": "teams",
  "teams.label.singular": "team",
  "teams.label.plural": "teams",
  "players.label.singular": "player",
  "players.label.plural": "players",
  "dialog.invoicesForCategory": "Invoices for category",
  "dialog.listContains": "This list contains",
  "dialog.playerSingular": "player",
  "dialog.playersPlural": "players",
  "search.playerPlaceholder": "Search for a player",
  "summary.total": "Total",
  "summary.paid": "Paid",
  "invoices.none": "No invoices available.",
  "button.close": "Close",
  "players.noneInCategory": "No player found in this category.",
  "stats.totalInvoiced": "Total Invoiced",
  "stats.totalPaid": "Total Paid",
  "stats.unpaid": "Unpaid",
  "stats.overdue": "Overdue",
  "auth.forgotPassword": "Forgot password",
  "auth.resetEmailSentTitle": "Email sent",
  "auth.resetEmailSentDescription":
    "A password reset link has been sent to your email address. It may take up to one minute to arrive. Don’t forget to check your spam folder.",
  "common.error": "Error",
  "auth.resetEmailError": "Unable to send the email.",
  "auth.resetPasswordDescription": "Enter your email to receive a reset link",
  "passwordReset.emailLabel": "Email",
  "passwordReset.emailPlaceholder": "your.email@rwdm.be",
  "passwordReset.sending": "Sending…",
  "passwordReset.send": "Send",
  "passwordReset.headerTitle": "Password Reset",
  "passwordReset.headerDescription": "Enter your new password to continue.",
  "passwordReset.newPasswordLabel": "New Password",
  "passwordReset.changing": "Changing…",
  "passwordReset.changePassword": "Change Password",
  "passwordReset.postChangeInfo":
    "Once your password has been changed, you’ll be able to log in with your new credentials.",
  "passwordReset.toastTitle": "Password Changed",
  "passwordReset.toastDescription": "You can now log in.",
  "toast.errorTitle": "Error",
  "toast.errorDescription": "An error occurred.",
  "toast.captchaRequiredTitle": "Captcha required",
  "toast.captchaRequiredDescription":
    "Please complete the captcha before submitting.",
  "toast.missingFieldsTitle": "Missing fields",
  "toast.missingFieldsDescription": "Please complete all the fields.",
  "toast.loginSuccessTitle": "Login successful",
  "toast.loginSuccessDescription": "Welcome to the admin dashboard",
  "toast.messageSentTitle": "Message sent",
  "toast.messageSentDescription":
    "Thank you, your message has been forwarded to the administration.",
  "toast.sendErrorTitle": "Error",
  "toast.sendErrorDescription": "Unable to send the message at this time.",
  "emails.title": "Emails",
  "emails.description": "Customize automatic emails sent to users.",
  "emails.guide": "User Guide",
  "emails.variables.info":
    "Use the {variables} available below to automatically customize the content of your emails with recipient data.",
  "emails.union.info": "For emails sent to the Belgian Union:",
  "emails.union.attachments":
    "Attached documents (accident report, certificate) will be automatically included as attachments",
  "emails.union.format": "PDF format is used for all documents",
  "emails.variables": "Available variables:",
  "emails.subject": "Subject",
  "emails.text": "Text",
  "emails.subject.placeholder": "Email subject",
  "emails.body.placeholder": "Email body",
  "emails.types": "Email types",
  "emails.edit": "Edit",
  "emails.preview": "Preview",
  "emails.save": "Save",
  "emails.saving": "Saving...",
  "emails.requests": "Requests",
  "emails.confirmations": "Confirmations",
  "emails.union": "Belgian Union Submissions",
  "emails.appointments": "Appointments",
  "emails.color": "Color",
  "emails.color.red": "Red",
  "emails.color.blue": "Blue",
  "emails.color.green": "Green",
  "emails.variables.available": "Available variables:",
  "emails.variables.playerName": "Player name",
  "emails.variables.accidentDate": "Accident date",
  "emails.variables.description": "Description",
  "emails.variables.clubName": "Club",
  "emails.variables.parentEmail": "Parent email",
  "emails.variables.documentType": "Document type",
  "emails.variables.date": "Date",
  "emails.variables.time": "Time",
  "emails.variables.type": "Type",
  "emails.variables.admin": "Admin",
  "emails.variables.notes": "Notes",
  "emails.color.placeholder": "Choose a color",
  "emails.preview.mode": "Preview",
  "emails.edit.mode": "Edit",
  saving: "Saving...",
  save_changes: "Save changes",
  "emails.guide.title": "User Guide",
  "emails.guide.instructions":
    "Use the {variables} available below to automatically customize your email content with recipient data.",
  "emails.guide.union.title": "For emails sent to the Belgian Union:",
  "emails.guide.union.attachments":
    "Attached documents (accident report, certificate) will be automatically included as attachments",
  "emails.guide.union.format": "PDF format is used for all documents",
  "email.type.registration": "Registration Request",
  "email.type.selection": "Selection Test Request",
  "email.type.accident": "Accident Report",
  "email.type.healing": "Healing Certificate",
  "email.type.waiver": "Liability Waiver",
  "email.type.registration_confirmed": "Registration Confirmation",
  "email.type.selection_confirmed": "Test Confirmation",
  "email.type.accident_confirmed": "Accident Confirmation",
  "email.type.healing_confirmed": "Healing Confirmation",
  "email.type.waiver_confirmed": "Waiver Confirmation",
  "email.type.accident_notify": "Accident Notification (Union)",
  "email.type.healing_notify": "Healing Notification (Union)",
  "email.type.appointment_scheduled": "Appointment Confirmation",
  "email.type.appointment_cancelled": "Appointment Cancellation",
  "emails.field.subject": "Subject",
  "emails.field.text": "Text",
  "emails.type.requests": "Requests",
  "emails.type.confirmations": "Confirmations",
  "emails.type.union": "Belgian Union Submissions",
  "emails.type.appointments": "Appointments",
  "email.type.accident-report": "Accident Report",
  "email.type.healing-certificate": "Healing Certificate",
  "email.type.accident-notify": "Accident Notification (Union)",
  "email.type.healing-notify": "Healing Notification (Union)",
  "emails.category.requests": "Requests",
  maintenance_active: "Ongoing maintenance",
  "forms.maintenance.title": "Forms Maintenance",
  "forms.maintenance.description":
    "Enable or disable maintenance mode for specific forms.",
  "forms.maintenance.registration_desc":
    "Put the registration form in maintenance.",
  "forms.maintenance.selection_desc":
    "Put the selection tests form in maintenance.",
  "forms.maintenance.accident_desc":
    "Put the accident report form in maintenance.",
  "forms.maintenance.waiver_desc":
    "Put the liability waiver form in maintenance.",
  brussels: "Brussels",
  toast_new_request_title: "New request received",
  toast_new_request_description:
    "A new {{type}} request from {{name}} has arrived.",
  request_type_registration: "Academy Registration",
  request_type_selection_tests: "Selection Tests",
  request_type_accident_report: "Accident Report",
  request_type_responsibility_waiver: "Responsibility Waiver",
  status_unknown: "Unknown",
  please_select_date_first: "Please select a date first",
  admin_auto_assigned: "Auto-assigned",
  today_appointments: "Appointments for today",
  no_appointments_today: "No appointments for today.",
  appointment_singular: "appointment",
  appointments_plural: "appointments",
  dropdown_send_email: "Send email",
  "dialog.overdueWarning":
    "Warning: these members have overdue payments that require prompt action.",
  "search.playerWithOverduePlaceholder":
    "Search for a player with overdue payments...",
  days: "days",
  "summary.balance": "Balance",
  "overdue.none": "No overdue payments.",
  "button.print": "Print",
  totalPlayersAcademy: "Total academy players",
  withoutDuplicateWarning:
    "This number may include players counted in multiple teams",
  withoutDuplicates: "Without duplicates",
  withDuplicates: "With duplicates",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  archiveSelected: "Archive Selected",
  archivingInProgress: "Archiving in Progress",
  exitArchiveMode: "Exit Archive Mode",
  archiveMode: "Archive Mode",
  select: "Select",
  accident_form_documents: "Documents",
  accident_form_documents_desc:
    "Please upload the required documents for the accident report.",
  preview: "Preview",
  file_uploaded_success: "File uploaded successfully",
  file_upload_error: "Error uploading file",
  pdf_only: "Only PDF files are allowed",
  file_too_large: "File size exceeds the limit of 2MB",
  file_too_large_5mb: "File size exceeds the limit of 5MB",
  download_error_title: "Download Error",
  download_error_description: "Unable to download the file.",
  pdf_not_available: "PDF not available",
  not_available: "Not available",
  pdf_not_configured: "The PDF generation is not configured for this request.",
  "filters.allSeasons": "All seasons",
  appointments_archive_mode: "Mode archive des rendez-vous",
  appointment_date: "Date",
  appointment_time: "Time",
  appointment_type: "Type",
  appointment_client: "Client",
  appointment_email: "Email",
  appointment_admin: "Admin",
  archive_success: "Archiving successful",
  archive_error: "Archiving error",
  no_selected_appointments: "No appointments selected",
  "All seasons": "All seasons",
  desktop_view_unavailable: "View unavailable",
  desktop_view_message:
    "This admin interface is only accessible on desktop computers.",
  "request_type.registration": "Academy Registration",
  "request_type.selection_tests": "Selection Tests",
  "request_type.accident_report": "Accident Report",
  "request_type.responsibility_waiver": "Liability Waiver",

  "status.new": "New",
  "status.assigned": "Assigned",
  "status.in_progress": "In Progress",
  "status.completed": "Completed",
  "status.rejected": "Rejected",
  "status.unknown": "Unknown",

  "common.signature": "Signature",
  "common.signature_alt": "Signature",
  "common.signature_date": "Signature date",
  "common.unknown_request_type": "Unknown request type.",

  "request.id_and_date": "Request #{id} • {date}",
  "request.submitted_on": "Submitted on",

  "registration.season_title": "Registration season",
  "registration.season": "Season",
  "registration.academy": "Academy",
  "registration.player_info": "Player information",
  "registration.lastName": "Last name",
  "registration.firstName": "First name",
  "registration.birthDate": "Birth date",
  "registration.birthPlace": "Birth place",
  "registration.address": "Address",
  "registration.postalCode": "Postal code",
  "registration.city": "City",
  "registration.currentClub": "Current club",
  "registration.category": "Category",
  "registration.primary_guardian": "Primary guardian information",
  "registration.guardian_type": "Type",
  "registration.phone": "Phone",
  "registration.email": "Email",
  "registration.gsm": "Mobile",
  "registration.secondary_guardian": "Secondary guardian information",
  "registration.image_consent": "Image consent",
  "registration.consent": "Consent",
  "registration.consent_accepted":
    "I agree that photos of my child may be taken and used for promotional purposes.",
  "registration.consent_declined": "Not consented",

  "selection.test_info": "Test information",
  "selection.category": "Category",
  "selection.academy": "Academy",
  "selection.player_info": "Player information",
  "selection.lastName": "Last name",
  "selection.firstName": "First name",
  "selection.birthDate": "Birth date",
  "selection.phone": "Phone (mobile)",
  "selection.email": "Email",
  "selection.currentClub": "Current club",
  "selection.previousClub": "Previous club",
  "selection.position": "Position",
  "selection.guardian_info": "Legal guardian information",
  "selection.relation": "Relation",

  "accident.info_title": "Accident information",
  "accident.date": "Accident date",
  "accident.academy": "Academy",
  "accident.playerLastName": "Player last name",
  "accident.playerFirstName": "Player first name",
  "accident.email": "Email address",
  "accident.phone": "Phone number",
  "accident.codeDossier": "Case code",
  "accident.documentLabel": "Document type",
  "accident.description_title": "Accident description",
  "accident.no_description": "No description provided.",
  "accident.supporting_documents": "Supporting documents",
  "accident.supporting_document": "Supporting document",
  "accident.view_document": "View document",
  "accident.view_pdf": "View PDF document",
  "accident.data_consent":
    'For efficient handling of my case, and only for this purpose, I authorize the processing of my medical data related to the accident of which I was a victim, as described in the "Privacy Declaration".',

  "waiver.parent_info": "Parent/guardian information",
  "waiver.lastName": "Last name",
  "waiver.firstName": "First name",
  "waiver.phone": "Phone",
  "waiver.email": "Email",
  "waiver.player_info": "Player information",
  "waiver.birthDate": "Birth date",
  "waiver.currentClub": "Current club",
  "waiver.waiver_title": "Liability waiver",
  "waiver.waiver_text":
    "I, the undersigned {parentFirstName} {parentLastName}, legal representative of player {playerFirstName} {playerLastName}, born on {playerBirthDate}, and affiliated with club {currentClub}, hereby release RWDM Academy from any liability for accidents that may occur during training sessions and/or friendly matches.",
  "waiver.date_confirmation": "Date and confirmation",
  "waiver.signatureDate": "Signature date",
  "waiver.approvalText": "Mention",
  "waiver.generate_pdf": "Generate PDF",
  "waiver.pdf_title": "Liability Waiver",
  "waiver.pdf_filename": "Liability_Waiver.pdf",
  "waiver.waiver_text_part1": "I, the undersigned",
  "waiver.waiver_text_part2": "legal representative of player",
  "waiver.waiver_text_part3": "born on",
  "waiver.waiver_text_part4": "and affiliated with club",
  "waiver.waiver_text_part5":
    "hereby release RWDM Academy from any liability for accidents that may occur during training sessions and/or friendly matches.",
  "email.type.refus_registration": "Registration rejection",
  "email.type.refus_selection": "Test rejection",
  "email.type.refus_accident": "Accident report rejection",
  "email.type.refus_healing": "Healing certificate rejection",
  "email.type.refus_waiver": "Waiver rejection",
  playerName: "Player name",
  requestId: "Request ID",
  parentName: "Parent name",
  club: "Club",
  appointmentDate: "Appointment date",
  appointmentTime: "Appointment time",
  appointmentType: "Appointment type",
  adminName: "Administrator",
  notes: "Notes",
  sidebar_requests: "Requests",
  sidebar_confirmations: "Confirmations",
  sidebar_refusals: "Refusals",
  sidebar_union: "Belgian Union Submissions",
  sidebar_appointments: "Appointments",
  accident_notify: "Accident Notification (Union)",
  healing_notify: "Recovery Notification (Union)",
  rejection: "Rejection",
  "api.settings.title": "API Settings",
  "api.settings.description":
    "Change your Pro Soccer Data API connection details. You'll find the information you need in the Pro Soccer Data control panel, in the Club API menu.",
  "api.settings.baseUrl": "Base URL",
  "api.settings.clubKey": "Club Key",
  "api.settings.apiKey": "API Key",
  "api.settings.apiSecret": "API Secret",
  "api.settings.secretNote":
    "This is a secret key used to authenticate API requests.",
  "api.settings.loadError": "Unable to load settings",
  "api.settings.loadErrorDetails": "Unable to load API settings.",
  "api.settings.saveSuccess": "Settings saved successfully",
  "api.settings.saveError": "Unable to save settings",
  "api.settings.saveErrorDetails":
    "Unable to save API settings. Please check your input.",
  "api.settings.validationError": "Invalid input",
  "api.settings.requiredFields": "Please fill in all required fields.",
  "api.settings.testConnection": "Test connection",
  "api.settings.testing": "Testing…",
  "api.settings.testSuccess": "Connection successful",
  "api.settings.testFailed": "Connection failed",
  "api.settings.testError": "Unable to test connection",
  "api.settings.testErrorDetails":
    "Unable to connect to the API. Please check your settings.",
  "api.success":
    "Successful connection with Pro Soccer Data! Your API settings are working correctly.",
  "contactForm.emailDisclaimer":
    "Please note that this email address is not monitored. For any inquiries, please use the contact form.",
  "auth.accessBlocked": "Access blocked",
  "auth.tokenError": "Token error",
  "maintenance.toggled": "Maintenance mode changed",
  "maintenance.enabled": "enabled",
  "maintenance.disabled": "disabled",
  "maintenance.toggleError": "Error toggling maintenance mode",
  "settings.saveSuccess": "Settings saved successfully",
  "settings.serverError": "Server error",
  "common.unknown": "Unknown",
  "logout.success": "Logout successful",
  "logout.message": "You have been logged out.",
  "button.exportExcel": "Export CSV",
  "forms.maintenance.message_label": "Custom maintenance message",
  "forms.maintenance.message_placeholder":
    "Enter your custom maintenance message here...",
  "maintenance.default_message":
    "This form is temporarily unavailable due to maintenance.",
  "maintenance.default_message_registration":
    "The registration form is temporarily unavailable due to maintenance.",
  "maintenance.default_message_selection":
    "The selection tests form is temporarily unavailable due to maintenance.",
  "maintenance.default_message_accident":
    "The accident report form is temporarily unavailable due to maintenance.",
  "maintenance.default_message_waiver":
    "The liability waiver form is temporarily unavailable due to maintenance.",
  "maintenance.title": "Maintenance in progress",
  "maintenance.back_button": "Back",
  form: "Form",
  "common.expand": "Expand",
  "common.collapse": "Collapse",
  account_reactivated: "Account successfully reactivated",
  account_not_found: "Account not found",
  server_error: "Server error",
  database: "Database",
  "database.usage_title": "Database Usage",
  "database.total_storage": "Total Storage",
  "database.pending_requests": "Pending Requests",
  "database.completed_requests": "Completed Requests",
  "database.appointments": "Appointments",
  "database.free_space": "Free Space",
  "database.usage_label": "Usage",
  "database.total_capacity": "Total Capacity",
  "database.megabytes": "MB",
  "database.chart_description":
    "This data represents the current database storage usage by content type.",
  "database.pending_requests_value": "Pending requests: {value} MB",
  "database.completed_requests_value": "Completed requests: {value} MB",
  "database.appointments_value": "Appointments: {value} MB",
  "database.free_space_value": "Free space: {value} MB and Usage: {value}%",
  "database.usage_percentage": "Usage: {value}%",
  "database.total_capacity_percentage": "Total capacity: 100%",
  "database.fetch_error": "Error loading storage data",
  "database.data_error": "Unable to load data",
  "database.storage_settings": "Storage settings",
  "database.storage_settings_desc":
    "Configure the total storage capacity and hosting provider",
  "database.total_capacity_mb": "Total capacity (MB)",
  "database.capacity_note":
    "Enter the total capacity your hosting provider allocates to you",
  "database.provider_name": "Hosting provider name",
  "database.update_settings": "Update settings",
  "database.updating_settings": "Updating...",
  "database.settings_fetch_error": "Loading error",
  "database.settings_fetch_error_desc": "Unable to load storage settings",
  "database.invalid_capacity": "Invalid capacity",
  "database.invalid_capacity_desc": "Capacity must be a positive number",
  "database.invalid_provider": "Invalid provider name",
  "database.invalid_provider_desc":
    "Please enter a valid hosting provider name",
  "database.settings_updated": "Settings updated",
  "database.settings_updated_desc":
    "Storage settings have been successfully updated",
  "database.settings_update_error": "Update error",
  "database.settings_update_error_desc": "Unable to update storage settings",
  "database.host_info": "Host Information",
  "database.hosting_details": "Database hosting details",
  "database.host_name": "Host Name",
  "database.allocated_storage": "Allocated Storage",
  "database.settings_error": "Update error",
  "database.settings_error_desc": "Unable to update hosting settings",
  items: "items",
  user_guide: "User Guide",
  "guide.client": "Visitor",
  "guide.client_intro": "Visitor Guide",
  "guide.client_desc":
    "This guide helps you understand how to use the platform as a parent, player, or representative, and how to submit the various available forms.",
  "guide.video_placeholder": "Tutorial Video",
  "guide.client_features": "Main Features",
  "guide.dashboard": "Dashboard",
  "guide.dashboard_desc":
    "Quickly access available forms and useful information for your request.",
  "guide.requests": "Forms",
  "guide.requests_desc":
    "Submit a registration request, selection test, accident report, or liability waiver. Track the status of your requests through email notifications.",
  "guide.appointments": "Recovery Certificate",
  "guide.appointments_desc":
    "Submit your recovery certificate once your injury has healed, using the case code received by email.",
  "guide.admin_intro": "Administrator Guide",
  "guide.admin_desc":
    "This guide covers the features available to administrators for managing requests and appointments.",
  "guide.admin_video": "Administrator Tutorial",
  "guide.admin_features": "Administrator Features",
  "guide.request_management": "Request Management",
  "guide.request_management_desc":
    "Handle the requests assigned to you and track their status.",
  "guide.planning": "Planning",
  "guide.planning_desc": "Manage the appointment calendar and availability.",
  "guide.documents": "Documents",
  "guide.documents_desc": "Access the document library and manage files.",
  "guide.superadmin_intro": "Super Administrator Guide",
  "guide.superadmin_desc":
    "This guide covers the advanced features available to super administrators.",
  "guide.superadmin_video": "Super Administrator Tutorial",
  "guide.superadmin_features": "Super Administrator Features",
  "guide.user_management": "User Management",
  "guide.user_management_desc":
    "Create, edit, and manage user accounts and permissions.",
  "guide.settings": "Settings",
  "guide.settings_desc":
    "Configure general application settings and advanced options.",
  "guide.database": "Database",
  "guide.database_desc": "View and manage database usage statistics.",
  "guide.owner_intro": "Owner Guide",
  "guide.owner_desc":
    "This guide details the exclusive features available to the application owner.",
  "guide.owner_video": "Owner Tutorial",
  "guide.owner_features": "Owner Features",
  "guide.analytics": "PSD Data",
  "guide.analytics_desc":
    "Access detailed reports and information from the PSD API.",
  "guide.branding": "Full Access",
  "guide.branding_desc":
    "Have full access to all application features, including interface and email customization.",
  "guide.integrations": "API Initialization",
  "guide.integrations_desc": "Initialize API authentication from PSD.",
  "guide.rights_management": "Rights Management",
  "guide.rights_management_desc":
    "Assign specific rights to admins and superadmins to manage access and permissions.",
  reset_user_password: "Reset user password",
  enter_new_password_for_user: "Enter new password for user",
  "guide.request_assignment": "Request Management",
  "guide.request_assignment_desc":
    "Assign requests or appointments to an administrator",
  "guide.archives": "Archives",
  "guide.archives_desc":
    "Manage application archives and stored data structure.",
  "guide.email_management": "Email Management",
  "guide.email_management_desc": "Customize automated emails sent to users.",
  "guide.developer_access": "Developer Access",
  "guide.github_repo": "GitHub Repository",
  "guide.github_repo_link": "Access RWDM Academy repository",
  "guide.tech_stack": "Tech Stack",
  "guide.tech_stack_desc":
    "The application is built using the following technologies:",
  "guide.api_docs": "API Documentation",
  "guide.api_docs_desc":
    "Complete API documentation is available for authorized developers in the Readme of the repository.",
};
