export const translationsNL = {
  welcome:
    "Welkom op de officiële RWDM Academy registratie platform. Selecteer het type formulier dat u wilt invullen.",
  contact: "Contact",
  about: "Over ons",
  home: "Startpagina",
  logout: "Afmelden",
  submit: "Verzenden",
  approved: "Gelezen en goedgekeurd",
  admin_space: "Beheerdersgebied",
  champ: "* : Verplicht veld",
  champ2: "Informatiepictogram (muis erover)",
  choose_language: "Kies uw taal",
  cancel: "Annuleren",
  academy_registration: "Inschrijvingsaanvraag voor de academie",
  academy_registration_desc:
    "Inschrijvingsformulier om lid te worden van de RWDM Academy",
  selection_tests: "Selectietestaanvraag",
  selection_tests_desc: "Inschrijving voor de selectietesten van de academie",
  accident_report: "Ongevallenverklaring",
  accident_report_desc: "Formulier om een ongeval te melden",
  liability_waiver: "Aansprakelijkheidsontheffing",
  liability_waiver_desc: "Formulier voor aansprakelijkheidsontheffing",
  admin_dashboard: "Dashboard",
  admin_documents: "Documentbeheer",
  admin_planning: "Planning",
  admin_members: "Leden",
  admin_graphics: "Statistieken",
  admin_settings: "Instellingen",
  admin_logout: "Afmelden",
  admin_panel: "Beheer",
  admin_rwdm: "RWDM Beheer",
  privacy_policy: "Privacybeleid",
  terms_and_conditions: "Algemene gebruiksvoorwaarden",
  legal_notice: "Wettelijke vermeldingen",
  cookie_policy: "Cookiebeleid",
  email_unavailable: "E-mail niet beschikbaar",
  legal_info: "Wettelijke informatie",
  all_rights_reserved: "Alle rechten voorbehouden.",
  footer_description:
    "De RWDM Academy is toegewijd aan de opleiding van jong Belgisch voetbaltalent. Wij engageren ons om een kwaliteitsvolle leeromgeving te bieden.",
  about_title: "Over RWDM Academy",
  about_subtitle:
    "Ontdek ons verhaal, onze missie en ons team dat zich inzet voor de ontwikkeling van jong talent.",
  players_trained: "Opgeleide profspelers",
  years_experience: "Jaren ervaring",
  national_trophies: "Betrokken teams",
  young_talents: "Jonge talenten",
  tab_history: "Geschiedenis",
  tab_mission: "Missie",
  tab_approach: "Aanpak",
  history_title: "Geschiedenis",
  mission_title: "Onze missie",
  approach_title: "Onze aanpak",
  academies_title: "Onze academies",
  rwdm_academy: "RWDM Aca.",
  bef_academy: "BEF Aca.",
  rfe_academy: "RFE Aca.",
  values_title: "Onze waarden",
  team_title: "Ons team",
  no_team_members:
    "Er zijn momenteel geen teamleden geregistreerd in het platform.",
  contact_title: "Neem contact met ons op",
  contact_description:
    "Heb je vragen? Aarzel niet om ons te contacteren. Ons team staat klaar om je te helpen.",
  send_us_message: "Stuur ons een bericht",
  contact_name: "Naam",
  contact_email: "E-mail",
  contact_subject: "Onderwerp",
  contact_message: "Bericht",
  contact_submit: "Bericht verzenden",
  contact_office_hours: "Openingsuren secretariaat",
  contact_address_title: "Ons adres",
  contact_email_title: "E-mail",
  contact_info_title: "Informatie",
  contact_account_name: "Rekeningnaam",
  contact_vat_number: "BTW-nummer",
  contact_company_number: "Ondernemingsnummer",
  contact_closed: "Gesloten",
  how_to_find_us: "Hoe ons te vinden",
  day_lundi: "Maandag",
  day_mardi: "Dinsdag",
  day_mercredi: "Woensdag",
  day_jeudi: "Donderdag",
  day_vendredi: "Vrijdag",
  day_samedi: "Zaterdag",
  day_dimanche: "Zondag",
  closed: "Gesloten",
  contact_select_subject: "Kies een onderwerp",
  contact_subject_registration: "Vraag over een inschrijvingsaanvraag",
  contact_subject_selection: "Vraag over de selectietesten",
  contact_subject_waiver: "Vraag over een aansprakelijkheidsontheffing",
  contact_subject_accident: "Ongevallenverklaring",
  contact_subject_recruitment: "Werving",
  contact_subject_incident: "Incident",
  contact_subject_technical: "Technisch probleem",
  contact_subject_other: "Anders",
  inbox: "Inbox",
  auth_title: "Authenticatie",
  auth_subtitle: "Toegang voorbehouden aan gemachtigd personeel",
  auth_email_label: "E-mail",
  auth_email_placeholder: "jouw.email@rwdm.be",
  auth_password_label: "Wachtwoord",
  auth_forgot_password: "Wachtwoord vergeten?",
  auth_login_button: "Inloggen",
  auth_logging_in: "Bezig met inloggen...",
  auth_admin_note:
    "Deze pagina is alleen toegankelijk voor RWDM Academy beheerders.",
  auth_login_success: "Succesvol ingelogd",
  auth_login_success_desc: "Welkom op het beheerderspaneel",
  auth_login_error: "Inlogfout",
  auth_login_error_desc: "Controleer je inloggegevens.",
  // Saison
  season_selection: "Inschrijvingsseizoen",
  season_selection_desc:
    "Selecteer het seizoen waarvoor u de speler wilt inschrijven",
  select_season_placeholder: "Selecteer een seizoen",

  // Académie
  academy_selection: "Academie",
  academy_selection_desc:
    "Selecteer de gewenste academie voor de inschrijving van de speler",
  select_academy_placeholder: "Selecteer een academie",

  // Informations joueur
  player_info: "Spelerinformatie",
  player_info_desc: "Vul alle informatie in over de speler",
  label_last_name: "Achternaam *",
  label_first_name: "Voornaam *",
  label_birth_date: "Geboortedatum *",
  label_birth_place: "Geboorteplaats *",
  label_address: "Adres *",
  label_postal_code: "Postcode *",
  label_city: "Stad *",
  label_current_club: "Huidige club",
  tooltip_current_club: "Als de speler geen club heeft, kunt u het leeg laten.",
  label_category: "Categorie *",
  select_category_placeholder: "Selecteer een categorie",

  // Responsables légaux
  legal_info_desc:
    "Vul de gegevens in van de wettelijke vertegenwoordigers van de speler",
  primary_guardian: "Hoofdverantwoordelijke",
  label_guardian_type: "Type *",
  select_type_placeholder: "Selecteer het type",
  option_father: "Vader",
  option_mother: "Moeder",
  option_legal_guardian: "Wettelijke voogd",
  label_parent_last_name: "Achternaam *",
  label_parent_first_name: "Voornaam *",
  label_parent_phone: "Telefoon *",
  label_parent_email: "E-mail *",
  label_parent_address: "Adres *",
  label_parent_postal_code: "Postcode *",
  label_parent_gsm: "GSM",
  secondary_guardian_button: "Tweede verantwoordelijke (optioneel)",

  // Consentement image
  consent_image: "Beeldtoestemming",
  consent_image_desc: "Geef uw toestemming voor het gebruik van afbeeldingen",
  consent_image_label:
    "Ik geef toestemming dat er foto's van mijn kind worden genomen en gebruikt voor promotionele doeleinden.",

  // Signature
  signature: "Handtekening",
  signature_desc: "Onderteken hieronder",
  signature_reminder_html:
    "<strong>Ter herinnering :</strong> dit formulier betreft een <u>inschrijvingsaanvraag</u> bij de RWDM Academy en vormt op geen enkele wijze een definitieve inschrijving. U ontvangt binnen enkele uren of dagen een reactie van de directie via het e-mailadres dat u hebt opgegeven.",
  label_date: "Datum :",

  // Politique
  accept_policy_html:
    'Ik ga akkoord met het <a href="/legal" class="underline text-rwdm-blue" target="_blank" rel="noopener noreferrer">privacybeleid</a>.',

  // Bouton & cooldown
  button_submit: "Verzend de inschrijvingsaanvraag",
  button_submit_loading: "Even geduld aub...",
  cooldown_message: "U kunt een nieuwe inschrijving versturen in {{time}}",

  // Vérification orthographique
  spellcheck_title: "Controle van inschrijvingsgegevens",
  spellcheck_title_2: "Verificatie van aangiftegegevens",
  spellcheck_field_player_last_name: "Achternaam van de speler",
  spellcheck_field_player_first_name: "Voornaam van de speler",
  spellcheck_field_parent1_last_name: "Achternaam hoofdverantwoordelijke",
  spellcheck_field_parent1_first_name: "Voornaam hoofdverantwoordelijke",
  spellcheck_field_parent1_email: "E-mailadres hoofdverantwoordelijke",
  spellcheck_field_parent2_last_name: "Achternaam tweede verantwoordelijke",
  spellcheck_field_parent2_first_name: "Voornaam tweede verantwoordelijke",
  spellcheck_field_parent2_email: "E-mailadres tweede verantwoordelijke",
  signature_placeholder: "Hier tekenen",
  clear: "Wissen",
  academy_info_html:
    'Meer informatie over onze academies vind je op de pagina <a href="/about?tab=histoire#academies" class="underline text-rwdm-blue hover:text-rwdm-red transition-colors">Over ons</a>.',
  spellcheck_description:
    "Controleer en bevestig elk veld door het vakje aan te vinken.",
  spellcheck_not_provided: "Niet ingevuld",
  spellcheck_modify: "Wijzigen",
  spellcheck_confirm_submit: "Bevestigen en verzenden",
  select_date_placeholder: "Selecteer een datum",
  toast_success_title: "Formulier verzonden",
  toast_success_description:
    "Je inschrijvingsaanvraag is met succes verzonden.",
  toast_error_title: "Fout",
  toast_error_description:
    "Er is een fout opgetreden bij het verzenden van het formulier.",
  toast_birthdate_missing_title: "Fout",
  toast_birthdate_missing_desc: "Selecteer de geboortedatum van de speler.",
  toast_age_invalid_title: "Ongeldige leeftijd",
  toast_age_invalid_desc:
    "De speler moet tussen 4 en 9 jaar oud zijn om zich in te schrijven.",
  // NL
  formType_registration: "inschrijving",
  formType_selectionTests: "selectietesten",
  formType_accidentReport: "ongevallenmelding",
  formType_responsibilityWaiver: "aansprakelijkheidsformulier",

  form_submission_success: "Formulier {{formType}} succesvol verzonden!",
  form_submission_desc1:
    "Uw aanvraag is geregistreerd en wordt door ons team verwerkt.",
  form_submission_desc2:
    "U ontvangt een bevestigingsmail en wordt op de hoogte gehouden van de updates.",

  form_submission_warning_title: "Let op",
  form_submission_warning_text:
    "Om veiligheidsredenen dient u ten minste 10 minuten te wachten voordat u een nieuw formulier indient.",

  return_home: "Terug naar startpagina",
  // NL
  selection_tests_section_title: "Informatie over de tests",
  selection_tests_section_subtitle: "Selecteer de categorie en de academie",

  selection_error_start_date_past_title: "Fout",
  selection_error_start_date_past_desc:
    "De begindatum mag niet in het verleden liggen.",
  selection_error_end_date_past_title: "Fout",
  selection_error_end_date_past_desc:
    "De einddatum mag niet in het verleden liggen.",
  selection_error_end_before_start_title: "Fout",
  selection_error_end_before_start_desc:
    "De einddatum kan niet vóór de begindatum liggen.",

  selection_player_section_title: "Spelerinformatie",
  selection_player_section_subtitle: "Vul alle gegevens van de speler in",

  selection_label_category: "Categorie *",
  selection_placeholder_category: "Selecteer een categorie",
  selection_label_academy: "Academie *",
  selection_placeholder_academy: "Selecteer een academie",
  selection_label_last_name: "Achternaam *",
  selection_label_first_name: "Voornaam *",
  selection_label_birth_date: "Geboortedatum *",
  selection_label_phone: "Telefoon (GSM) van speler",
  selection_label_email: "E-mail van speler",
  selection_label_current_club: "Huidige club van speler",
  selection_tooltip_current_club:
    "Als de speler geen club heeft, kunt u dit leeg laten.",
  selection_label_previous_club: "Vorige club van speler",
  selection_tooltip_previous_club:
    "Als de speler nog nooit in een club speelde, kunt u dit leeg laten.",
  selection_label_position: "Positie *",
  selection_placeholder_position: "Selecteer een positie",
  selection_position_default: "Veldspeler (U5-U9)",

  selection_legal_section_title: "Gegevens wettelijke vertegenwoordiger",
  selection_legal_section_subtitle:
    "Vul de gegevens in van de wettelijke vertegenwoordiger van de speler. Bent u meerderjarig? U kunt 'Wettelijk vertegenwoordiger' kiezen.",

  selection_label_parent_last_name: "Achternaam *",
  selection_label_parent_first_name: "Voornaam *",
  selection_label_parent_phone: "Telefoon (GSM) van verantwoordelijke *",
  selection_label_parent_email: "E-mail van verantwoordelijke *",
  selection_label_parent_relation: "Relatie *",
  selection_placeholder_parent_relation: "Selecteer de relatie",
  selection_option_parent: "Ouder",
  selection_option_representative: "Wettelijk vertegenwoordiger",

  selection_signature_section_title: "Handtekening",
  selection_signature_section_subtitle:
    "Onderteken om uw inschrijving voor de selectietests te bevestigen",
  selection_signature_info:
    "De RWDM Academy is niet aansprakelijk voor incidenten, ongevallen of diefstal in of rond haar faciliteiten. Door te ondertekenen erkent u daarvan op de hoogte te zijn.",
  selection_signature_label:
    "Handtekening van speler of ouder/wettelijk vertegenwoordiger (voor minderjarigen)",
  selection_signature_placeholder:
    "Onderteken hier om uw inschrijving voor de tests te bevestigen",

  selection_accept_policy_html:
    'Ik ga akkoord met het <a href="/legal" class="underline text-rwdm-blue" target="_blank" rel="noopener noreferrer">privacybeleid</a>.',

  selection_button_submit: "Verzend testaanvraag",
  selection_button_cooldown: "Even geduld aub ({{time}})",
  selection_cooldown_message:
    "U kunt weer een testaanvraag indienen over {{time}}",

  selection_spellcheck_title: "Controle van testgegevens",
  selection_spellcheck_field_player_last_name: "Achternaam speler",
  selection_spellcheck_field_player_first_name: "Voornaam speler",
  selection_spellcheck_field_player_email: "E-mail speler",
  selection_spellcheck_field_parent_last_name: "Achternaam ouder",
  selection_spellcheck_field_parent_first_name: "Voornaam ouder",
  selection_spellcheck_field_parent_email: "E-mail ouder",

  selection_error_birthdate_missing_title: "Fout",
  selection_error_birthdate_missing_desc:
    "Selecteer de geboortedatum van de speler.",
  selection_error_age_invalid_title: "Ongeldige leeftijd",
  selection_error_age_invalid_desc:
    "De speler moet tussen 4 en 20 jaar oud zijn om deel te nemen aan de technische test.",
  selection_error_academy_missing_title: "Fout",
  selection_error_academy_missing_desc: "Selecteer een academie.",
  selection_success_submission_title: "Formulier verzonden",
  selection_success_submission_description:
    "Uw testaanvraag is succesvol verzonden.",
  selection_error_submission_title: "Fout",
  selection_error_submission_description:
    "Er is een fout opgetreden bij het versturen van het formulier.",
  category_U5: "U5",
  category_U6: "U6",
  category_U7: "U7",
  category_U8: "U8",
  category_U9: "U9",
  category_U10: "U10",
  category_U11: "U11",
  category_U12: "U12",
  category_U13: "U13",
  category_U14: "U14",
  category_U15_full: "U15 (beschikbaar bij RFE Academy)",
  category_U16: "U16",
  category_U17_full: "U17 (beschikbaar bij RFE Academy)",
  category_U18: "U18",
  category_U19_full: "U19 (beschikbaar bij RFE Academy)",
  category_U21: "U21",

  position_goalkeeper: "Doelman",
  position_right_back: "Rechtsback",
  position_left_back: "Linksback",
  position_center_back: "Centrale verdediger",
  position_defensive_mid: "Verdedigende middenvelder",
  position_central_mid: "Controlerende middenvelder",
  position_attacking_mid: "Offensieve middenvelder",
  position_right_wing: "Rechtsbuiten",
  position_left_wing: "Linksbuiten",
  position_striker: "Spits",
  academy_RWDM_elite: "RWDM Academy (Elite)",
  academy_RFE_provincial: "Red For Ever Academy (Provincialen)",
  selection_error_date_past_title: "Fout",
  selection_error_date_past_desc: "De datum mag niet in het verleden liggen.",
  accident_info_alert_title: "Belangrijk",
  accident_info_alert_html: `
      Zorg ervoor dat u uw verklaring binnen maximaal <span class="text-red-500 font-semibold">19 dagen</span> na het ongeval indient. De negentiende dag kan worden geweigerd. Na deze termijn kan de aanvraag niet meer in behandeling worden genomen.
      <br/><br/>
      De verklaring wordt eerst goedgekeurd door de club en vervolgens door de KBVB verwerkt. De medische kosten zijn in eerste instantie voor uw eigen rekening.
      <br/><br/>
      Na genezing moet u op deze pagina uw genezingscertificaat en de kosten van uw arts uploaden. Deze documenten worden ook door de club goedgekeurd voordat ze naar de KBVB worden gestuurd voor eventuele terugbetaling.
      <br/><br/>
      <span class="font-semibold text-gray-700 dark:text-gray-300">
        Download ook de PDF hieronder, laat uw arts deze invullen en voeg hem toe als PDF-bestand bij de ongevalsaangifte.
      </span>`,
  accident_section_title: "Gegevens over het ongeval",
  accident_section_subtitle: "Geef de basisinformatie over het ongeval op",
  label_accident_date: "Datum van het ongeval *",
  tooltip_accident_date: "U mag geen toekomstige datum selecteren.",
  label_club_name: "Naam van de club *",
  placeholder_category: "Selecteer een categorie",
  label_player_first_name: "Voornaam van de speler *",
  label_player_last_name: "Achternaam van de speler *",
  label_email: "E-mailadres *",
  label_phone: "Telefoonnummer *",
  label_accident_description: "Beschrijving van het ongeval *",
  placeholder_accident_description:
    "Beschrijf hoe het ongeval is gebeurd, waar, wanneer en de directe gevolgen...",
  accident_description_counter: "{{count}}/700 tekens",
  document_section_title: "Bewijzendocument",
  document_section_subtitle:
    "Kies het type document en upload een PDF (medisch verslag, enz.)",
  tabs_accident_report: "Ongevalsaangifte",
  tabs_healing_certificate: "Genezingscertificaat",
  label_accident_code: "Dossiercode",
  placeholder_accident_code: "Klik op ‘Genereren’ om een code te krijgen",
  button_generate_code: "Genereren",
  accident_code_info_html:
    'Deze code is essentieel om later het genezingscertificaat uit te reiken. <span class="ml-1 font-medium text-red-500">Zonder deze code</span> kunt u geen genezingscertificaat koppelen aan deze aangifte.',
  upload_click_to_upload:
    '<span class="font-semibold">Klik om te uploaden</span> of sleep hierheen',
  upload_guidance_pdf: "Tot {{max}} bestanden (PDF, JPG, PNG – max. 10 MB elk)",
  upload_guidance_single: "1 PDF-bestand (MAX. 10MB)",
  button_remove_file: "Verwijderen",
  checkbox_healing_sent: "Ik heb al een ongevalsaangifte verzonden",
  label_healing_code: "Dossiercode ontvangen bij de aangifte *",
  placeholder_healing_code: "Bijv.: XG72ZL",
  healing_code_valid:
    "Code geldig! Het dossier is gekoppeld aan het e-mailadres: {{email}}",
  healing_code_invalid: "Geen dossier gevonden voor deze code en e-mailadres.",
  healing_upload_prompt: "Upload hier uw genezingscertificaat:",
  signature_section_title: "Handtekening",
  signature_section_subtitle:
    "Onderteken om de juistheid van de informatie te bevestigen",
  signature_privacy_html: `
      Voor een efficiënte afhandeling van mijn dossier geef ik alleen voor dit doel toestemming voor de verwerking van mijn medische gegevens met betrekking tot het ongeval waarvan ik het slachtoffer ben, zoals beschreven in de
      <a href="https://arena-nv.be/fr/products/4" class="text-blue-600 underline" target="_blank" rel="noopener noreferrer">
        Privacyverklaring</a>.
      Conform de AVG heb ik recht op inzage, rectificatie, overdraagbaarheid, bezwaar en verwijdering van mijn gegevens (arena@arena-nv.be).`,
  signature_label_html:
    "<strong>Handtekening van het slachtoffer of de ouders/voogd (voor kinderen onder de 18 jaar)</strong>",
  signature_placeholder_decla:
    "Onderteken hier om de ongevalsaangifte te bevestigen",
  cooldown_message_html:
    "U kunt weer een aangifte indienen in <strong>{{time}}</strong>",
  spellcheck_field_email: "E-mailadres",
  spellcheck_field_phone: "Telefoonnummer",
  label_academy: "Academie *",
  placeholder_select_academy: "Selecteer een academie",
  not_provided: "Niet ingevuld",
  button_submit_accident: "Verzend de aangifte",
  button_submit_accident_loading: "Even geduld aub...",
  toast_too_many_files_title: "Te veel bestanden",
  toast_too_many_files_desc: "Maximaal {{max}} bestand{{plural}} toegestaan.",
  toast_invalid_file_title: "Ongeldig bestand",
  toast_invalid_file_desc:
    "Alleen PDF-, JPG- of PNG-bestanden kleiner dan 10 MB zijn toegestaan.",
  toast_file_error_title: "Fout bestand",
  toast_file_error_healing_desc:
    "Voeg ten minste één PDF-bestand toe (max. 2).",
  toast_file_error_accident_desc:
    "Voeg een PDF-bestand toe voor de ongevalsaangifte.",
  toast_invalid_code_title: "Ongeldige dossiercode",
  toast_invalid_code_desc:
    "Voer een geldige code van een bestaande aangifte in.",
  toast_upload_error_title: "Uploadfout",
  toast_upload_error_desc:
    "Er is een fout opgetreden tijdens het uploaden van het bestand.",
  toast_upload_too_large_title: "Bestand te groot",
  toast_upload_too_large_desc: "Selecteer bestanden kleiner dan 10 MB.",
  toast_submit_success_title: "Aangifte succesvol verzonden",
  toast_submit_success_desc: "Uw aangifte is verzonden.",
  toast_general_error_title: "Fout",
  toast_general_error_desc:
    "Er is een fout opgetreden bij het verzenden van het formulier.",
  document_label_accident: "Ongevalsaangifte",
  document_label_healing: "Geneescertificaat",
  medical_download_button: "Download medisch formulier",
  medical_dialog_title: "Kies de taal van het formulier",
  medical_dialog_description:
    "Het PDF-formulier is beschikbaar in het Frans of Nederlands.",
  medical_language_fr: "Frans",
  medical_language_nl: "Nederlands",
  toast_download_title: "Download gestart",
  toast_download_desc_fr: "Het Franstalige formulier wordt gedownload.",
  toast_download_desc_nl: "Het Nederlandstalige formulier wordt gedownload.",
  date_invalid_title: "Ongeldige datum",
  date_invalid_desc: "U kunt geen ongeval melden in de toekomst.",
  declaration_refused_title: "Aangifte geweigerd",
  declaration_refused_desc:
    "Uw aangifte kan niet meer in behandeling worden genomen, omdat het ongeval meer dan 19 dagen geleden heeft plaatsgevonden.",
  declaration_valid_title: "Aangifte geldig",
  declaration_valid_desc:
    "Uw ongevalsaangifte voldoet aan de limiet van 19 dagen.",
  toast_generate_code_title: "Code succesvol gegenereerd",
  toast_generate_code_desc:
    "Bewaar deze code goed om later uw geneescertificaat te koppelen.",
  parse_data_error: "Kan gegevens niet parsen voor aanvraag-ID {{id}}",
  check_code_general_error: "Fout bij het verifiëren van de code",
  waiver_player_info_title: "Spelerinformatie",
  waiver_player_info_subtitle: "Vul de informatie over de speler in",
  label_player_birth_date: "Geboortedatum *",

  waiver_parent_info_title: "Informatie over ouder/voogd",
  waiver_parent_info_subtitle:
    "Vul uw gegevens in als wettelijke vertegenwoordiger. Bent u speler en meerderjarig? U mag uw eigen gegevens invullen.",
  waiver_waiver_title: "Aansprakelijkheidsontheffing",
  waiver_waiver_subtitle: "Lees aandachtig voordat u tekent",

  waiver_date_confirmation_title: "Datum en bevestiging",
  waiver_date_confirmation_subtitle:
    "Bevestig de datum en voer 'Gelezen en goedgekeurd' in",
  label_waiver_date: "Handtekeningdatum",
  label_approval_text: 'Vermelding "Gelezen en goedgekeurd"',
  placeholder_approval_text: "Selecteer uw akkoord",
  option_approval_text: "Gelezen en goedgekeurd",

  signature_placeholder_waiver:
    "Onderteken hier om de aansprakelijkheidsontheffing te bevestigen",

  button_submit_waiver: "Verzend de ontheffing",
  cooldown_message_waiver_html:
    "U kunt de aansprakelijkheidsontheffing opnieuw verzenden in {{time}}",

  spellcheck_title_waiver: "Controle van de ontheffingsgegevens",
  spellcheck_field_parent_first_name: "Voornaam verantwoordelijke",
  spellcheck_field_parent_last_name: "Achternaam verantwoordelijke",
  spellcheck_field_parent_email: "E-mail verantwoordelijke",

  toast_error_description_required: "Vul alle verplichte velden in.",
  toast_success_waiver_title: "Ontheffing succesvol verzonden",
  toast_success_waiver_description:
    "Uw aansprakelijkheidsontheffing is verzonden.",
  toast_error_generic_description:
    "Er is een fout opgetreden tijdens het verzenden van het formulier.",
  toast_error_upload_signature: "Fout bij uploaden van de handtekening.",
  toast_error_api: "API-fout.",
  waiver_text_template:
    "Ondergetekende, {{parentFirstName}} {{parentLastName}}, wettelijke vertegenwoordiger van de speler {{playerFirstName}} {{playerLastName}}, geboren op {{playerBirthDate}}, en aangesloten bij club {{currentClub}}, ontheft RWDM Academy van alle verantwoordelijkheid in geval van een ongeval tijdens trainingen en/of vriendschappelijke wedstrijden waaraan de speler vanaf vandaag deelneemt.",
  tab_confidentiality: "Privacybeleid",
  tab_terms: "Gebruiksvoorwaarden",
  tab_legal: "Juridische Vermelding",
  tab_cookies: "Cookies",
  btn_back_home: "Terug naar start",
  page_legal_title: "Juridische informatie",
  confidentiality_title: "Privacybeleid",
  confidentiality_last_updated: "Laatst bijgewerkt:",
  confidentiality_section1_title: "1. Inleiding",
  confidentiality_section1_text:
    "Welkom op het RWDM Academy-platform. Wij zetten ons in voor de bescherming van de privacy en persoonsgegevens van de gebruikers van onze dienst. Dit privacybeleid legt uit hoe we uw persoonlijke gegevens verzamelen, gebruiken, delen en beschermen.",
  confidentiality_section2_title: "2. Verzamelde gegevens",
  confidentiality_section2_intro:
    "We verzamelen de volgende gegevens tijdens uw gebruik:",
  confidentiality_li_name: "Naam, voornaam, geboortedatum en geboorteplaats",
  confidentiality_li_contact: "Adres, postcode, stad, e-mail, telefoon (gsm)",
  confidentiality_li_sport:
    "Inschrijvingsseizoen, academie, categorie, positie",
  confidentiality_li_club: "Huidige en vorige club",
  confidentiality_li_responsible:
    "Type verantwoordelijke (vader/moeder/voogd), naam, voornaam, telefoon, e-mail, adres",
  confidentiality_li_consent:
    "Beeldtoestemming en handtekening (datum, vermelding “Gelezen en goedgekeurd”)",
  confidentiality_li_accident:
    "Datum en beschrijving van het ongeval, dossiercode, PDF-bewijsdocument",
  confidentiality_li_navigation:
    "Navigatiegegevens (opgeslagen in localStorage)",
  confidentiality_li_minors:
    "Minderjarigen jonger dan 18 jaar mogen deze formulieren niet invullen.",
  confidentiality_section3_title: "3. Gebruik van gegevens",
  confidentiality_section3_li1:
    "Beheren van uw aanvragen (inschrijving, test, ongeval, vrijwaring)",
  confidentiality_section3_li2:
    "Contact met u opnemen voor afspraken en opvolging",
  confidentiality_section3_li3:
    "Onze dienstverlening en de veiligheid van het platform verbeteren",
  confidentiality_section4_title: "4. Rechtsgrondslag van de verwerking",
  confidentiality_section4_li1: "Uitdrukkelijke toestemming",
  confidentiality_section4_li2: "Contractuele uitvoering",
  confidentiality_section4_li3: "Legitiem belang",
  confidentiality_section4_li4: "Wettelijke verplichtingen",
  confidentiality_section5_title: "5. Delen van gegevens",
  confidentiality_section5_li1: "URBSFA voor officiële inschrijvingen",
  confidentiality_section5_li2: "IT‑dienstverleners",
  confidentiality_section5_li3:
    "Bevoegde autoriteiten indien wettelijk vereist",
  confidentiality_section5_text:
    "We verkopen uw persoonsgegevens nooit aan derden.",
  confidentiality_section6_title: "6. Bewaartermijn",
  confidentiality_section6_li1:
    "Duur van de aanvraagverwerking en bijbehorende opvolging",
  confidentiality_section6_li2: "Wettelijke bewaartermijnen",
  confidentiality_section6_li3: "Tot 3 jaar na de laatste activiteit",
  confidentiality_section7_title: "7. Uw rechten",
  confidentiality_section7_li1: "Recht op toegang, rectificatie, wissen",
  confidentiality_section7_li2: "Recht op beperking en overdraagbaarheid",
  confidentiality_section7_li3:
    "Recht van verzet en intrekking van toestemming",
  confidentiality_section7_contact:
    "Om deze rechten uit te oefenen, neem contact op met",
  confidentiality_section8_title: "8. Gegevensbeveiliging",
  confidentiality_section8_text:
    "We passen technische en organisatorische maatregelen toe om uw gegevens te beschermen tegen verlies, ongeautoriseerde toegang en openbaarmaking.",
  confidentiality_section9_title: "9. Internationale overdrachten",
  confidentiality_section9_text:
    "Gegevens worden opgeslagen en verwerkt in de Europese Unie. Elke overdracht buiten de EU is gedekt door GDPR-conforme waarborgen.",
  confidentiality_section10_title: "10. Contact",
  confidentiality_section10_text: "Voor vragen, schrijf naar",
  last_updated: "Laatst bijgewerkt",
  confidentiality_section3_intro: "We gebruiken uw gegevens om:",
  confidentiality_section3_text:
    "We gebruiken uw gegevens om: uw aanvragen te verwerken (inschrijving, selectie‑tests, ongevalsaangifte, vrijwaring), contact met u op te nemen voor afspraken en opvolging, onze diensten en de beveiliging van het platform te verbeteren.",
  cgu_title: "Algemene Gebruiksvoorwaarden",
  cgu_section1_title: "1. Acceptatie van de voorwaarden",
  cgu_section1_text:
    "Door verzoeken via het RWDM Academy‑platform te verzenden, stemt u in met deze Algemene Gebruiksvoorwaarden. Als u niet akkoord gaat, gebruik dan onze service niet.",
  cgu_section2_title: "2. Beschrijving van de dienst",
  cgu_section2_text1:
    "Het RWDM Academy‑platform maakt het mogelijk om verzoeken in te dienen voor:",
  cgu_section2_li1: "inschrijvingsverzoek voor de RWDM‑academie",
  cgu_section2_li2: "verzoek om selectie‑tests",
  cgu_section2_li3: "ongevalsaangifte",
  cgu_section2_li4: "ondertekening van een vrijwaring",
  cgu_section2_text2:
    "U ontvangt een automatische ontvangstbevestiging per e‑mail, gevolgd door een definitieve bevestiging (acceptatie, afspraak, vervolg) per e‑mail.",
  cgu_section3_title: "3. Toegang en indieningsvoorwaarden",
  cgu_section3_text1: "Om een verzoek in te dienen, moet u:",
  cgu_section3_li1:
    "Minstens 18 jaar oud zijn of, indien minderjarig, vertegenwoordigd door een ouder/voogd",
  cgu_section3_li2: "Nauwkeurige, volledige en actuele informatie verstrekken",
  cgu_section3_li3: "Alle toepasselijke wetten naleven",
  cgu_section4_title: "4. Beheer van beheerdersaccounts",
  cgu_section4_text:
    "Alleen owner, superadmin en admin hebben handmatig aangemaakte accounts door de eigenaar. Eindgebruikers hebben geen account‑aanmaakfunctionaliteit.",
  cgu_section5_title: "5. Acceptabel gebruik",
  cgu_section5_text1: "U stemt ermee in niet:",
  cgu_section5_li1: "De service te beschadigen of onbeschikbaar te maken",
  cgu_section5_li2: "Valse of misleidende informatie in te dienen",
  cgu_section5_li3:
    "Te proberen toegang te krijgen tot verzoeken of accounts van anderen",
  cgu_section5_li4: "Ongeautoriseerde geautomatiseerde middelen te gebruiken",
  cgu_section5_li5: "Beveiligingsmaatregelen te omzeilen",
  cgu_section6_title: "6. Intellectuele eigendom",
  cgu_section6_text:
    "Alle inhoud (logo’s, teksten, afbeeldingen) is beschermd. Elk gebruik zonder schriftelijke toestemming is verboden.",
  cgu_section7_title: "7. Aansprakelijkheid",
  cgu_section7_text:
    "De service wordt geleverd “zoals het is” en “indien beschikbaar”. We garanderen geen ononderbroken beschikbaarheid en zijn niet aansprakelijk voor indirecte schade.",
  cgu_section8_title: "8. Wijziging van de voorwaarden",
  cgu_section8_text:
    "We kunnen deze voorwaarden op elk moment wijzigen. Wijzigingen worden van kracht bij publicatie; voortgezet gebruik geldt als acceptatie.",
  cgu_section9_title: "9. Beëindiging",
  cgu_section9_text:
    "We kunnen de toegang schorsen of beëindigen bij schending. U kunt op elk moment verzoeken om verwijdering van uw gegevens.",
  cgu_section10_title: "10. Toepasselijk recht en jurisdictie",
  cgu_section10_text:
    "Deze voorwaarden worden beheerst door Belgisch recht. Elk geschil wordt voorgelegd aan de rechtbanken van Brussel.",
  cgu_section11_title: "11. Contact",
  cgu_section11_text:
    "Voor vragen kunt u contact opnemen met: RWDM Academy, Rue Charles Malis 61, 1080 Molenbeek‑Saint‑Jean, {{email}}",
  cgu_section2_intro:
    "Het RWDM Academy-platform stelt u in staat om aanvragen in te dienen voor:",
  cgu_section2_item1: "aanvraag voor inschrijving bij de RWDM-academie",
  cgu_section2_item2: "aanvraag selectieproef",
  cgu_section2_item3: "ongevallenmelding",
  cgu_section2_item4: "ondertekening van een vrijwaringsformulier",
  cgu_section2_text:
    "U ontvangt een automatische ontvangstbevestiging per e-mail en later een bevestiging (acceptatie, afspraak, vervolg) per e-mail.",
  cgu_section3_intro: "Om een aanvraag in te dienen moet u:",
  cgu_section3_item1:
    "Minimaal 18 jaar oud zijn of, indien minderjarig, vertegenwoordigd door een ouder/voogd",
  cgu_section3_item2:
    "Nauwkeurige, volledige en actuele informatie verstrekken",
  cgu_section3_item3: "Alle toepasselijke wetten naleven",
  cgu_section5_intro: "U verbindt zich ertoe niet te:",
  cgu_section5_item1: "De service te beschadigen of onbeschikbaar te maken",
  cgu_section5_item2: "Valse of misleidende informatie in te dienen",
  cgu_section5_item3:
    "Te proberen toegang te krijgen tot aanvragen of accounts van anderen",
  cgu_section5_item4: "Ongeautoriseerde geautomatiseerde middelen te gebruiken",
  cgu_section5_item5: "Beveiligingsmaatregelen te omzeilen",
  cgu_section11_contact_intro: "Voor vragen kunt u contact opnemen met:",

  // Sectie 1
  legal_section1_title: "1. Wettelijke informatie",
  legal_section1_intro: "Dit platform wordt uitgegeven door:",
  legal_section1_name_label: "Naam",
  legal_section1_address_label: "Adres",
  legal_section1_country_label: "Land",
  legal_section1_email_label: "E‑mail",

  // Sectie 2
  legal_section2_title: "2. Publicatieverantwoordelijke",
  legal_section2_text:
    "De verantwoordelijke uitgever is Nawfel Ajari, software engineer bij <a href='https://www.nainnovations.be' target='_blank' rel='noopener noreferrer' style='text-decoration: underline; color: #6b7280;' onmouseover='this.style.color=\"#4b5563\"' onmouseout='this.style.color=\"#6b7280\"'>NA Innovations</a>.",

  legal_section2_subtitle: "Technische ontwikkeling",
  legal_section2_dev_text: "De site is ontwikkeld door Nawfel Ajari.",

  // Sectie 3
  legal_section3_title: "3. Hosting",
  legal_section3_intro: "Dit platform wordt gehost door:",
  legal_section3_provider: "Hostinger",
  legal_section3_address:
    "Adres: Hostinger International Ltd, 61 Lordou Vironos Street, 6023 Larnaca, Cyprus",
  legal_section3_website: "Website: https://www.hostinger.com",

  // Sectie 4
  legal_section4_title: "4. Intellectueel eigendom",
  legal_section4_text:
    "Alle inhoud (teksten, afbeeldingen, logo’s, enz.) is exclusief eigendom van RWDM Academy of haar partners. Elk gebruik zonder schriftelijke toestemming is verboden.",

  // Sectie 5
  legal_section5_title: "5. Hyperlinks",
  legal_section5_text:
    "Het platform kan links naar andere sites bevatten. Wij hebben geen controle over de inhoud en wijzen alle aansprakelijkheid af.",

  // Sectie 6
  legal_section6_title: "6. Aansprakelijkheid",
  legal_section6_text:
    "Wij streven naar nauwkeurigheid van informatie. Wij garanderen echter geen volledigheid of juistheid en wijzen alle aansprakelijkheid voor weglatingen of onjuistheden af.",

  // Sectie 7
  legal_section7_title: "7. Toepasselijk recht en jurisdictie",
  legal_section7_text:
    "Deze wettelijke vermeldingen vallen onder Belgisch recht. In geval van geschil zijn alleen de rechtbanken van Brussel bevoegd.",
  cookie_policy_title: "Cookiebeleid",
  cookie_policy_last_updated: "Laatst bijgewerkt",
  cookie_section1_title: "1. Geen HTTP‑cookies",
  cookie_section1_text:
    "We gebruiken geen HTTP‑cookies. Alle voorkeuren (taal, weergave) worden in client‑side localStorage opgeslagen.",
  cookie_section2_title: "2. Waarom geen cookies?",
  cookie_section2_text: "Door voorkeuren in localStorage op te slaan, :",
  cookie_section2_point1: "Verminderen we HTTP‑overhead (geen cookie‑headers)",
  cookie_section2_point2:
    "Bewaren we gegevens langer zonder automatische vervaldatum",
  cookie_section2_point3:
    "Vermijden we grootte‑ en parseerbeperkingen van cookies",
  cookie_section3_title: "3. Beheer van lokale opslag",
  cookie_section3_text:
    "U kunt localStorage wissen of uitschakelen via uw browser; dit zet uw voorkeuren (taal, thema, enz.) terug.",
  cookie_section4_title: "4. Functionele impact",
  cookie_section4_text:
    "Verwijdering van gegevens uit localStorage kan ervoor zorgen dat uw taal en instellingen bij elk bezoek terugvallen op de standaardwaarden.",
  cookie_section5_title: "5. Contact",
  cookie_section5_text:
    "Voor vragen over dit beleid kunt u contact opnemen met",
  cookie_section2_li1: "Verminderen HTTP‑verzoeken (geen cookie‑headers)",
  cookie_section2_li2:
    "Bewaren gegevens langer zonder automatische vervaldatum",
  cookie_section2_li3: "Vermijden grootte‑/parsing‑beperkingen van cookies",
  maintenance_title: "Formulieren in onderhoud",
  maintenance_message:
    "Onze formulieren zijn momenteel in onderhoud om uw ervaring te verbeteren. " +
    "Voor dit formulier " +
    "kunt u langs komen bij de directie binnen onze openingstijden.",
  thanks_patience: "We zijn snel weer terug. Dank voor uw geduld!",
  account_button: "Mijn account",
  logout_title: "Uitloggen",
  logout_message: "Weet je zeker dat je wilt uitloggen?",
  confirm_action_title: "Actie bevestigen",
  send_email_checkbox_label: "Bevestigingsmail verzenden",
  confirm: "Bevestigen",
  account: "Account",
  error: "Fout",
  success: "Succes",
  passwords_do_not_match: "Wachtwoorden komen niet overeen.",
  password_update_success: "Wachtwoord succesvol bijgewerkt.",
  password_update_error: "Fout bij het bijwerken.",
  server_error_password_update:
    "Serverfout bij het bijwerken van het wachtwoord.",
  change_password: "Wachtwoord wijzigen",
  enter_new_password: "Voer uw nieuwe wachtwoord in en bevestig het",
  new_password: "Nieuw wachtwoord",
  confirm_password: "Bevestig wachtwoord",
  update: "Bijwerken",
  assignments: "Toewijzingen",
  created_on: "Aangemaakt op",
  close: "Sluiten",
  function_label: "Functie",
  role_owner: "Owner",
  role_superadmin: "Superadmin",
  role_admin: "Beheerder",
  role_user: "Gebruiker",
  dashboard_title: "Dashboard",
  dashboard_description: "Beheer de aanvragen en volg hun voortgang",
  dashboard_view_planning: "Planning bekijken",
  requests: "Aanvragen",
  stats: "Statistieken",
  card_requests_title: "Lijst met aanvragen",
  card_requests_info:
    "Afgewezen aanvragen worden na 24 uur definitief uit de database verwijderd.",
  card_requests_assigned_label: "Mijn toewijzingen",
  toast_appointment_title: "Afspraak gepland",
  toast_appointment_desc_prefix: "Er is een afspraak toegevoegd voor",
  toast_appointment_desc_suffix: ".",
  toast_request_deleted_title: "Aanvraag verwijderd",
  toast_request_deleted_description: "De aanvraag is definitief verwijderd.",
  toast_request_auto_deleted_title: "Aanvraag automatisch verwijderd",
  toast_request_auto_deleted_description:
    "Aanvraag {{id}} is verwijderd na 24 uur.",
  toast_assign_error_title: "Fout",
  toast_assign_error_description: "Het toewijzen van de aanvraag is mislukt.",
  toast_status_updated_title: "Status bijgewerkt",
  toast_status_updated_description: 'De status is gewijzigd naar "{{status}}".',
  toast_status_error_title: "Fout",
  toast_status_error_description: "Kan de status niet wijzigen.",
  toast_accident_sent_title: "Aangifte verzonden",
  toast_accident_sent_description: "Het ongevalsrapport is verzonden.",
  toast_accident_error_title: "Fout",
  toast_accident_error_description:
    "Fout bij het verzenden van het ongevalsrapport.",
  toast_certificate_sent_title: "Certificaat verzonden",
  toast_certificate_sent_description:
    "Beide documenten zijn verzonden en als voltooid gemarkeerd.",
  toast_certificate_error_title: "Fout",
  toast_certificate_error_description:
    "Fout bij het verzenden van het certificaat.",
  search_filters_title: "Zoekfilters",
  search_input_placeholder: "Zoeken op naam, e-mail of ID...",
  select_all_admins: "Alle beheerders",
  select_unassigned: "Niet toegewezen",
  select_status_placeholder: "Status",
  select_all_statuses: "Alle statussen",
  status_new: "Nieuw",
  status_assigned: "Toegewezen",
  status_in_progress: "Bezig",
  status_completed: "Voltooid",
  status_rejected: "Geweigerd",
  select_all_types: "Alle types",
  form_type_registration: "Inschrijvingsaanvraag",
  form_type_selection_tests: "Selectietests",
  form_type_accident_report: "Ongeval",
  form_type_responsibility_waiver: "Vrijwaring",
  table_id: "ID",
  table_type: "Type",
  table_name: "Naam",
  table_status: "Status",
  table_assigned_to: "Toegewezen aan",
  table_date: "Datum",
  table_appointment: "Afspraak",
  table_actions: "Acties",
  table_no_results: "Geen enkele aanvraag komt overeen met je filters.",
  toast_assign_inactive_title: "Toewijzingsfout",
  toast_assign_inactive_description:
    "Je kunt geen inactieve gebruiker toewijzen.",
  label_inactive: "(inactief)",
  dropdown_view_request: "Aanvraag bekijken",
  dropdown_set_in_progress: "In behandeling zetten",
  dropdown_appointment: "Afspraak",
  toast_assign_required_title: "Toewijzing vereist",
  toast_accept_assign_required_desc:
    "Er moet een beheerder worden toegewezen voordat je kunt accepteren.",
  toast_reject_assign_required_desc:
    "Wijs eerst een beheerder toe voordat je kunt weigeren.",
  pagination_page_prefix: "Pagina ",
  pagination_page_separator: " van ",
  button_actions_title: "Acties",
  badge_status_new: "Nieuw",
  badge_status_assigned: "Toegewezen",
  badge_status_in_progress: "Bezig",
  badge_status_completed: "Voltooid",
  badge_status_rejected: "Geweigerd",
  badge_status_unknown: "Onbekend",
  pending_accidents_title: "In afwachting zijnde ongevallenaangiften",
  pending_accidents_info:
    "Ongevallenaangiften worden hier in afwachting gehouden van het bijbehorende genezingsattest.",
  valid_accidents_label: "Correct ingediende aangiften",
  dialog_edit_federation_email_title:
    "E-mailadres van de Belgische Bond bewerken",
  button_save: "Opslaan",
  placeholder_new_recipient: "Nieuwe ontvanger",
  table_header_id: "ID",
  table_header_accident_date: "Ongevaldatum",
  table_header_name: "Naam",
  table_header_status: "Status",
  table_header_assigned_to: "Toegewezen aan",
  table_header_deadline: "Uiterste datum",
  table_header_actions: "Acties",
  table_header_recipients: "Ontvangers",
  badge_label_in_progress: "Bezig",
  healing_certificate_received: "Genezingsattest ontvangen",
  pagination_prefix: "Pagina ",
  pagination_separator: " van ",
  confirm_send_declaration_title: "Verzenden naar de Belgische Bond",
  confirm_send_declaration_message:
    "Weet je zeker dat je dit ongevallenaangifteformulier naar de Belgische voetbalbond wilt verzenden?",
  confirm_send_healing_title: "Genezingsattest verzenden",
  confirm_send_healing_message:
    "Weet je zeker dat je dit genezingsattest naar de Belgische Bond wilt verzenden?",
  completed_requests_title_prefix: "Recent voltooide aanvragen (",
  completed_requests_title_separator: " weergegeven van de ",
  completed_requests_title_suffix: ")",
  no_completed_requests: "Nog geen voltooide aanvragen.",
  table_header_type: "Type",
  table_header_date: "Datum",
  button_view_completed_prefix: "Bekijk ",
  button_view_completed_suffix: " voltooide aanvragen",
  card_requests_stats_title: "Aanvraagstatistieken",
  label_new_requests: "Nieuwe aanvragen",
  label_requests_in_progress: "Lopende aanvragen",
  label_completed_requests: "Voltooide aanvragen",
  label_pending_accidents: "Ongevallen in behandeling",
  card_requests_evolution_title: "Evolutie van aanvragen over het jaar",
  chart_title_requests_by_type: "Aanvragen per type over het jaar",
  members_title: "Leden",
  members_subtitle: "Beheer de academieleden",
  planning_title: "Planning",
  planning_description: "Bekijk en beheer de afspraken bij het secretariaat",
  add_appointment: "Afspraak toevoegen",
  view_day: "Dagweergave",
  view_week: "Weekweergave",
  all_admins: "Alle beheerders",
  schedule_new_appointment: "Nieuwe afspraak plannen",
  appointment_date_label: "Afspraakdatum",
  appointment_time_label: "Afspraaktijd",
  appointment_type_label: "Type afspraak",
  type_registration: "Inschrijvingsaanvraag",
  type_selection_tests: "Selectietests",
  type_accident_report: "Ongevallenmelding",
  type_responsibility_waiver: "Aansprakelijkheidsverklaring",
  type_other: "Anders",
  person_name_label: "Naam van de persoon",
  person_name_placeholder: "Volledige naam invoeren",
  contact_email_label: "Contact e-mail",
  contact_email_placeholder: "voorbeeld@email.com",
  select_time_placeholder: "Selecteer een tijd",
  assigned_admin_label: "Toegewezen beheerder",
  select_admin_placeholder: "Selecteer een beheerder",
  no_admins_found: "Geen beheerder gevonden",
  notes_label: "Notities (optioneel)",
  notes_placeholder: "Voeg extra notities toe",
  cancel_button: "Annuleren",
  schedule_appointment_button: "Afspraak plannen",
  appointment_details_title: "Afspraakdetails",
  appointment_detail_client: "Klant :",
  appointment_detail_email: "Email :",
  appointment_detail_date: "Datum :",
  appointment_detail_time: "Tijd :",
  appointment_detail_type: "Type :",
  appointment_detail_admin: "Beheerder :",
  appointment_detail_notes: "Notities :",
  appointment_no_notes: "Geen notities",
  close_button: "Sluiten",
  calendar_title: "Kalender",
  legend_title: "Legenda",
  legend_with_appointments: "Dag met afspraak",
  legend_selected_day: "Geselecteerde dag",
  appointments_on: "Afspraken van",
  no_appointments: "Geen afspraken voor deze datum.",
  add_appointment_on_date: "Voeg een afspraak toe voor deze datum",
  registration_label: "Inschrijving",
  selection_tests_label: "Tests",
  accident_report_label: "Ongeval",
  responsibility_waiver_label: "Aansprakelijkheidsvrijwaring",
  other_label: "Anders",
  admin_label: "Beheerder :",
  no_admin_assigned: "Geen beheerder toegewezen",
  no_notes: "Geen notities",
  day_selected: "geselecteerde dag",
  legend_registration: "Inschrijving op de academie",
  legend_selection_tests: "Selectietests",
  legend_accident_report: "Ongevalsaangifte",
  legend_responsibility_waiver: "Aansprakelijkheidsvrijwaring",
  legend_other: "Anders",
  week_title_prefix: "Week van",
  week_title_middle: "tot",
  button_today: "Vandaag",
  table_header_time: "Tijd",
  label_available: "Beschikbaar",
  label_client: "Klant",
  filter_applied_title: "Filter toegepast",
  filter_applied_desc: "Uw planning toont nu alleen afspraken van",
  filter_cleared_title: "Filter gewist",
  page_docs_title: "Documentbeheer",
  page_docs_desc: "Vind hier de documenten van de leden",
  button_create_request: "Een aanvraag maken",
  completedRequests: "Voltooide aanvragen",
  statistics: "Statistieken",
  documents: "Documenten",
  noDocumentsMatch: "Geen documenten voldoen aan uw criteria.",
  generatePdfTitle: "PDF genereren",
  generatePdfMessage: "Wilt u echt het PDF-bestand van dit verzoek genereren?",
  revertToInProgressTitle: "Opnieuw in behandeling nemen",
  revertToInProgressMessage:
    "Wilt u dit verzoek echt op 'In behandeling' zetten?",
  searchFilters: "Zoekfilters",
  searchPlaceholder: "Zoeken op naam, voornaam, e-mail of telefoon…",
  allAdmins: "Alle beheerders",
  allTypes: "Alle types",
  registration: "Inschrijvingen",
  selectionTests: "Technische testen",
  responsibilityWaiver: "Aansprakelijkheidsverklaringen",
  accidentReport: "Ongevalsaangiften",
  tableHeaderID: "ID",
  tableHeaderType: "Type",
  tableHeaderName: "Naam",
  tableHeaderEmail: "E-mail",
  tableHeaderStatus: "Status",
  tableHeaderAssignedTo: "Toegewezen aan",
  tableHeaderDate: "Datum",
  tableHeaderActions: "Acties",
  completed: "Voltooid",
  viewDetails: "Bekijk details",
  edit: "Bewerken",
  setInProgress: "In behandeling zetten",
  generatePDF: "PDF genereren",
  previous: "Vorige",
  next: "Volgende",
  page: "Pagina",
  of: "van",
  create_member: "Lid aanmaken",
  all_members: "Alle leden",
  old_members: "Oude leden",
  roles_legend_title: "Legenda van rollen",
  role_owner_desc:
    "Platformdirecteur – volledige toegang tot alle functionaliteiten.",
  role_superadmin_desc:
    "Beheerverantwoordelijke – toegang tot instellingen, gebruikers en toewijzingen.",
  role_admin_desc:
    "Planningsbeheerder – toegang tot de planning en het dashboard.",
  members_registered: "Ingeschreven leden",
  table_header_avatar: "Avatar",
  table_header_full_name: "Volledige naam",
  table_header_email: "E-mail",
  table_header_function: "Functie",
  table_header_role: "Rol",
  table_header_created_at: "Aangemaakt op",
  no_member_found: "Geen lid gevonden",
  page_info: "Pagina",
  table_header_assignments: "Toewijzingen",
  table_header_deleted_at: "Verwijderd op",
  "button.restore_member": "Heractiveren",
  reactivateModalTitle: "Account opnieuw activeren",
  reactivateModalConfirmStart:
    "Weet u zeker dat u het account wilt reactiveren van",
  reactivateModalConfirmEnd: " ?",
  buttonCancel: "Annuleren",
  buttonConfirm: "Bevestigen",
  deleteMemberTitle: "Definitief verwijderen",
  deleteMemberMessage:
    "Weet u zeker dat u dit lid definitief wilt verwijderen? Deze actie is onomkeerbaar. Het laat de toewijzingen zonder verantwoordelijke achter.",
  noOldMembers: "Geen oud lid gevonden",
  "pagination.page": "Pagina",
  "pagination.of": "van",
  createMember: "Lid aanmaken",
  firstNamePlaceholder: "Voornaam",
  lastNamePlaceholder: "Achternaam",
  emailPlaceholder: "E-mail",
  passwordPlaceholder: "Wachtwoord",
  functionPlaceholder: "Functie",
  roleLabel: "Rol:",
  "button.create_member": "Lid aanmaken",
  "member.edit_title": "Lid bewerken",
  "member.edit_password_placeholder": "Leeg laten om niet te wijzigen",
  "button.save": "Opslaan",
  "deleteMember.title": "Lid verwijderen",
  "deleteMember.prompt": "Weet u zeker dat u dit lid wilt verwijderen",
  "button.cancel": "Annuleren",
  "button.delete": "Verwijderen",
  "chart.completedByMonth.title":
    "Voltooide aanvragen per maand en per beheerder",
  "chart.byAdminAndMonth.subtitle": "Per beheerder en per maand",
  "dialog.editRequest.titlePrefix": "Wijzig aanvraag #",
  clubName: "Club",
  playerLastName: "Achternaam speler",
  playerFirstName: "Voornaam speler",
  email: "E-mail",
  phone: "Telefoon",
  accidentDate: "Datum van het ongeval",
  description: "Beschrijving",
  filePaths: "Ondersteunende documenten",
  category: "Categorie",
  codeDossier: "Dossiercode",
  documentLabel: "Documenttype",
  parentLastName: "Achternaam ouder",
  parentFirstName: "Voornaam ouder",
  parentPhone: "Telefoon ouder",
  parentEmail: "E-mail ouder",
  playerBirthDate: "Geboortedatum speler",
  currentClub: "Huidige club",
  previousClub: "Vorige club",
  signatureDate: "Datum handtekening",
  approvalText: "Goedgekeurde tekst",
  filePath: "Bestandspad",
  season: "Inschrijvingsseizoen",
  academy: "Academie",
  lastName: "Achternaam speler",
  firstName: "Voornaam speler",
  birthDate: "Geboortedatum",
  birthPlace: "Geboorteplaats",
  address: "Adres",
  postalCode: "Postcode",
  city: "Stad",
  position: "Positie",
  parentRelation: "Relatie",
  parent1Type: "Relatie ouder 1",
  parent1LastName: "Achternaam ouder 1",
  parent1FirstName: "Voornaam ouder 1",
  parent1Phone: "Telefoon ouder 1",
  parent1Email: "E-mail ouder 1",
  parent1Address: "Adres ouder 1",
  parent1PostalCode: "Postcode ouder 1",
  parent1Gsm: "Mobiel ouder 1",
  parent2Type: "Relatie ouder 2",
  parent2LastName: "Achternaam ouder 2",
  parent2FirstName: "Voornaam ouder 2",
  parent2Phone: "Telefoon ouder 2",
  parent2Email: "E-mail ouder 2",
  parent2Address: "Adres ouder 2",
  parent2PostalCode: "Postcode ouder 2",
  parent2Gsm: "Mobiel ouder 2",
  imageConsent: "Beeldtoestemming",
  createdAt: "Aanmaakdatum",
  save: "Opslaan",
  enterClubName: "Voer Club in",
  enterPlayerLastName: "Voer achternaam speler in",
  enterPlayerFirstName: "Voer voornaam speler in",
  enterEmail: "Voer e-mail in",
  enterPhone: "Voer telefoonnummer in",
  enterAccidentDate: "Kies de datum van het ongeval",
  enterDescription: "Voer de beschrijving in",
  enterFilePaths: "Voeg ondersteunende documenten toe",
  enterSignature: "Voer handtekening in",
  enterCategory: "Voer de categorie in",
  enterCodeDossier: "Voer het dossiernummer in",
  enterDocumentLabel: "Voer het documenttype in",
  enterParentLastName: "Voer de achternaam van de ouder in",
  enterParentFirstName: "Voer de voornaam van de ouder in",
  enterParentPhone: "Voer het telefoonnummer van de ouder in",
  enterParentEmail: "Voer het e-mailadres van de ouder in",
  enterPlayerBirthDate: "Kies de geboortedatum van de speler",
  enterCurrentClub: "Voer de huidige club in",
  enterPreviousClub: "Voer de vorige club in",
  enterSignatureDate: "Kies de datum van ondertekening",
  enterApprovalText: "Voer de goedkeuringstekst in",
  enterFilePath: "Voer het bestandspad in",
  enterSeason: "Voer het seizoen in",
  enterAcademy: "Voer de academie in",
  enterLastName: "Voer de achternaam van de speler in",
  enterFirstName: "Voer de voornaam van de speler in",
  enterBirthDate: "Kies de geboortedatum",
  enterBirthPlace: "Voer de geboorteplaats in",
  enterAddress: "Voer het adres in",
  enterPostalCode: "Voer de postcode in",
  enterCity: "Voer de stad in",
  enterPosition: "Voer de positie in",
  enterParentRelation: "Voer de ouderrelatie in",
  enterParent1Type: "Voer relatie ouder 1 in",
  enterParent1LastName: "Voer achternaam ouder 1 in",
  enterParent1FirstName: "Voer voornaam ouder 1 in",
  enterParent1Phone: "Voer telefoon ouder 1 in",
  enterParent1Email: "Voer e-mail ouder 1 in",
  enterParent1Address: "Voer adres ouder 1 in",
  enterParent1PostalCode: "Voer postcode ouder 1 in",
  enterParent1Gsm: "Voer mobiel ouder 1 in",
  enterParent2Type: "Voer relatie ouder 2 in",
  enterParent2LastName: "Voer achternaam ouder 2 in",
  enterParent2FirstName: "Voer voornaam ouder 2 in",
  enterParent2Phone: "Voer telefoon ouder 2 in",
  enterParent2Email: "Voer e-mail ouder 2 in",
  enterParent2Address: "Voer adres ouder 2 in",
  enterParent2PostalCode: "Voer postcode ouder 2 in",
  enterParent2Gsm: "Voer mobiel ouder 2 in",
  enterImageConsent: "Voer beeldtoestemming in",
  enterCreatedAt: "Kies de aanmaakdatum",
  "toast.error": "Fout",
  "toast.emptyDetails": "Details mogen niet leeg zijn.",
  "toast.updated": "Bijgewerkt",
  "toast.updatedDesc": "Gegevens zijn succesvol bijgewerkt.",
  "toast.saveFailed": "Opslaan mislukt.",
  "dialog.editRequest.title": "Aanvraag bewerken",
  "appointmentDialog.title": "Kies het type afspraak",
  "appointmentDialog.description":
    "Selecteer het type afspraak voor de speler.",
  "appointment.scheduleTest": "Een technische test inplannen",
  "appointment.visitOffice": "Afspraak op het secretariaat",
  "settings.title": "Site-instellingen",
  "settings.description":
    "Pas het platform aan voor de klantzijde en beheer het onderhoud",
  "language.fr": "Frans",
  "language.nl": "Nederlands",
  "language.en": "Engels",
  "maintenance.enable": "Onderhoud activeren",
  "maintenance.disable": "Onderhoud deactiveren",
  "maintenance.toggling": "…",
  "maintenance.warning.title": "Let op",
  "maintenance.warning.content":
    "Wanneer een woord in één taal wordt gewijzigd, vergeet dan niet het in alle andere talen bij te werken om de",
  "maintenance.warning.highlight": "consistentie",
  "maintenance.warning.content2":
    ". Wanneer de onderhoudsmodus is ingeschakeld, worden alle bezoekers omgeleid naar een onderhoudsweergave in plaats van de formulieren.",
  "tabs.general": "Algemeen",
  "tabs.about": "Over",
  "tabs.contact": "Contact",
  "button.saveChanges": "Wijzigingen opslaan",
  "confirmation.saveSettings":
    "Weet u zeker dat u deze instellingen wilt opslaan?",
  "confirmation.updatedTranslations": "Ik heb alle vertalingen bijgewerkt.",
  "maintenance.confirmEnable": "Bevestig activering",
  "maintenance.confirmDisable": "Bevestig deactivering",
  "maintenance.confirmEnableMessage":
    "Weet je zeker dat je de onderhoudsmodus wilt activeren?",
  "maintenance.confirmDisableMessage":
    "Weet je zeker dat je de onderhoudsmodus wilt verlaten?",
  "settings.confirmSaveTitle": "Bevestig opslaan",
  "siteIdentity.title": "Identiteit van de site",
  "siteIdentity.description": "Kies de officiële kleuren van uw club.",
  "siteIdentity.unavailable": "Momenteel niet beschikbaar",
  "siteIdentity.color1Label": "Kleur 1 van de site",
  "siteIdentity.color2Label": "Kleur 2 van de site",
  "siteIdentity.logoLabel": "Logo (bestand)",
  "toasts.logoUploaded": "Logo succesvol geüpload !",
  "clubDetails.clubName": "Clubsnaam",
  "clubDetails.contactTitle": "Clubgegevens",
  "clubDetails.contactDesc": "Vul de adres- en locatiegegevens in.",
  "clubDetails.address": "Clubadres",
  "clubDetails.postalCode": "Postcode",
  "clubDetails.commune": "Gemeente",
  "clubDetails.country": "Land",
  "contactSocial.title": "Contact & sociale netwerken",
  "contactSocial.description":
    "Deze informatie wordt openbaar weergegeven op de site.",
  "contactForm.email": "E-mail",
  "contactForm.facebookUrl": "Facebook-URL",
  "contactForm.instagramUrl": "Instagram-URL",
  language_changed_title: "Taal gewijzigd",
  language_changed_desc: "De interface taal is bijgewerkt.",
  "clubStats.title": "Clubstatistieken",
  "clubStats.description":
    "Deze cijfers weerspiegelen de impact en geschiedenis van de club.",
  "clubAbout.title": "Over de club",
  "clubAbout.description":
    "Vul de kerninformatie in die de geschiedenis, missie en aanpak van de club presenteren.",
  tabsHistory: "Geschiedenis",
  tabsMission: "Missie",
  tabsApproach: "Aanpak",
  labelDescription: "Beschrijving",
  photoHistoryFile: "Foto Geschiedenis (bestand)",
  photoMissionFile: "Foto Missie (bestand)",
  photoApproachFile: "Foto Benadering (bestand)",
  maxSize: "Maximale omvang: 2 MB",
  "academies.title": "Onze academies",
  "academies.description":
    "Vul de naam, beschrijving en een afbeelding voor elke academie in.",
  "academies.tab1": "Academie 1",
  "academies.tab2": "Academie 2",
  "academies.tab3": "Academie 3",
  "academies.name1": "Naam Academie 1",
  "academies.name2": "Naam Academie 2",
  "academies.name3": "Naam Academie 3",
  "academies.desc1": "Beschrijving Academie 1",
  "academies.desc2": "Beschrijving Academie 2",
  "academies.desc3": "Beschrijving Academie 3",
  "academies.photo1": "Foto Academie 1 (bestand)",
  "academies.photo2": "Foto Academie 2 (bestand)",
  "academies.photo3": "Foto Academie 3 (bestand)",
  "academies.photoLabel": "Academie foto",
  academiesName1: "Academie naam",
  academiesDesc1: "Academie beschrijving",
  academiesUploadSuccess1: "Afbeelding voor Academie 1 succesvol geüpload!",
  academiesName2: "Academie naam",
  academiesDesc2: "Academie beschrijving",
  academiesUploadSuccess2: "Afbeelding voor Academie 2 succesvol geüpload!",
  academiesName3: "Academie naam",
  academiesDesc3: "Academie beschrijving",
  academiesUploadSuccess3: "Afbeelding voor Academie 3 succesvol geüpload!",
  valuesTitle: "Onze waarden",
  valuesDescription:
    "De club zet zich in om sterke waarden over te brengen zoals respect, fair play en teamgeest.",
  value1Title: "Waarde 1 Titel",
  value1TitlePlaceholder: "bijv. Respect, Fair-play…",
  value1Description: "Waarde 1 Beschrijving",
  value1DescriptionPlaceholder:
    "Beschrijf wat deze waarde voor de club betekent",

  value2Title: "Waarde 2 Titel",
  value2TitlePlaceholder: "bijv. Solidariteit, Teamgeest…",
  value2Description: "Waarde 2 Beschrijving",
  value2DescriptionPlaceholder: "Leg uit waarom deze waarde belangrijk is",

  value3Title: "Waarde 3 Titel",
  value3TitlePlaceholder: "bijv. Verantwoordelijkheid, Betrokkenheid…",
  value3Description: "Waarde 3 Beschrijving",
  value3DescriptionPlaceholder: "Geef details over deze waarde voor je leden",
  openingHoursTitle: "Openingstijden",
  openingHoursDescription:
    "Als zowel de openingstijd als de sluitingstijd op 00:00 staan, wordt de dag als gesloten beschouwd.",
  statusOpen: "Open",
  statusClosed: "Gesloten",
  "companyInfo.title": "Bedrijfsinformatie",
  "companyInfo.description":
    "Deze gegevens worden openbaar weergegeven op de Contact-pagina van de site.",
  "companyInfo.accountName": "Rekeningnaam",
  "companyInfo.vatNumber": "BTW-nummer",
  "companyInfo.companyNumber": "Bedrijfsnummer",
  statistics_title: "Statistieken",
  statistics_description:
    "Financieel beheer & piramide-hiërarchie van de academie",
  financialManagement: "Financieel beheer",
  hierarchy: "Hiërarchie",
  apiActive: "API actief",
  apiUnavailable: "API niet beschikbaar",
  hierarchyTitle: "Teamhiërarchie",
  hierarchyDesc1: "Gegevens geleverd door de API",
  hierarchyDesc2: "in realtime. Sommige namen kunnen dubbel voorkomen.",
  "filters.title": "Zoekfilters",
  "filters.searchPlayer": "Zoek een speler…",
  "filters.allCategories": "Alle categorieën",
  "invoices.byCategoryTitle": "Facturen per categorie",
  byCategory: "Verdeling per categorie",
  paymentsTrend: "Ontwikkeling van betalingen",
  paid: "Betaald",
  unpaid: "Onbetaald",
  invoiceList: "Factuurlijst",
  "invoiceList.date": "Factuurdatum",
  "invoiceList.number": "Nummer",
  "invoiceList.fullName": "Volledige Naam",
  "invoiceList.totalAmount": "Totaalbedrag",
  "invoiceList.paidAmount": "Betaald Bedrag",
  "invoiceList.team": "Team",
  "categoryCounts.title": "Statistieken per categorie",
  "categoryCounts.teamsSingular": "team",
  "categoryCounts.teamsPlural": "teams",
  "teams.label.singular": "team",
  "teams.label.plural": "teams",
  "players.label.singular": "speler",
  "players.label.plural": "spelers",
  "dialog.invoicesForCategory": "Facturen voor categorie",
  "dialog.listContains": "Deze lijst bevat",
  "dialog.playerSingular": "speler",
  "dialog.playersPlural": "spelers",
  "search.playerPlaceholder": "Zoek een speler",
  "summary.total": "Totaal",
  "summary.paid": "Betaald",
  "invoices.none": "Geen facturen beschikbaar.",
  "button.close": "Sluiten",
  "players.noneInCategory": "Geen speler gevonden in deze categorie.",
  "stats.totalInvoiced": "Totaal gefactureerd",
  "stats.totalPaid": "Totaal betaald",
  "stats.unpaid": "Openstaand",
  "stats.overdue": "Te laat",
  "auth.forgotPassword": "Wachtwoord vergeten",
  "auth.resetEmailSentTitle": "E-mail verzonden",
  "auth.resetEmailSentDescription":
    "Een link om je wachtwoord te resetten is verzonden naar je e-mailadres. Het kan tot één minuut duren voordat de link aankomt. Vergeet niet je spamfolder te controleren.",
  "common.error": "Fout",
  "auth.resetEmailError": "Kan de e-mail niet verzenden.",
  "auth.resetPasswordDescription":
    "Voer uw e-mail in om een link voor opnieuw instellen te ontvangen",
  "passwordReset.emailLabel": "E-mail",
  "passwordReset.emailPlaceholder": "uw.email@rwdm.be",
  "passwordReset.sending": "Verzenden…",
  "passwordReset.send": "Verzenden",
  "passwordReset.headerTitle": "Wachtwoordhersteling",
  "passwordReset.headerDescription":
    "Voer uw nieuwe wachtwoord in om door te gaan.",
  "passwordReset.newPasswordLabel": "Nieuw wachtwoord",
  "passwordReset.changing": "Wachtwoord wijzigen…",
  "passwordReset.changePassword": "Wachtwoord wijzigen",
  "passwordReset.postChangeInfo":
    "Zodra het wachtwoord is gewijzigd, kunt u inloggen met uw nieuwe gegevens.",
  "passwordReset.toastTitle": "Wachtwoord gewijzigd",
  "passwordReset.toastDescription": "Je kunt nu inloggen.",
  "toast.errorTitle": "Fout",
  "toast.errorDescription": "Er is een fout opgetreden.",
  "toast.captchaRequiredTitle": "Captcha vereist",
  "toast.captchaRequiredDescription": "Valideer de captcha voordat u verzendt.",
  "toast.missingFieldsTitle": "Verplichte velden",
  "toast.missingFieldsDescription": "Vul alstublieft alle velden in.",
  "toast.loginSuccessTitle": "Succesvolle aanmelding",
  "toast.loginSuccessDescription": "Welkom op het beheerderspaneel",
  "toast.messageSentTitle": "Bericht verzonden",
  "toast.messageSentDescription":
    "Bedankt, uw bericht is succesvol naar de administratie gestuurd.",
  "toast.sendErrorTitle": "Fout",
  "toast.sendErrorDescription":
    "Het is niet mogelijk het bericht op dit moment te verzenden.",
  "emails.title": "E-mails",
  "emails.description":
    "Pas automatische e-mails aan die naar gebruikers worden verzonden.",
  "emails.guide": "Gebruikersgids",
  "emails.variables.info":
    "Gebruik de {variables} hieronder om de inhoud van uw e-mails automatisch aan te passen met ontvangersgegevens.",
  "emails.union.info": "Voor e-mails verzonden naar de Belgische Bond:",
  "emails.union.attachments":
    "Bijgevoegde documenten (ongevalsaangifte, certificaat) worden automatisch als bijlagen toegevoegd",
  "emails.union.format": "PDF-formaat wordt gebruikt voor alle documenten",
  "emails.variables": "Beschikbare variabelen:",
  "emails.subject": "Onderwerp",
  "emails.text": "Tekst",
  "emails.subject.placeholder": "E-mail onderwerp",
  "emails.body.placeholder": "E-mail inhoud",
  "emails.types": "E-mail types",
  "emails.edit": "Bewerken",
  "emails.preview": "Voorbeeld",
  "emails.save": "Opslaan",
  "emails.saving": "Opslaan...",
  "emails.requests": "Aanvragen",
  "emails.confirmations": "Bevestigingen",
  "emails.union": "Belgische Bond Verzendingen",
  "emails.appointments": "Afspraken",
  "emails.color": "Kleur",
  "emails.color.red": "Rood",
  "emails.color.blue": "Blauw",
  "emails.color.green": "Groen",
  "emails.variables.available": "Beschikbare variabelen:",
  "emails.variables.playerName": "Naam speler",
  "emails.variables.accidentDate": "Ongevalsdatum",
  "emails.variables.description": "Beschrijving",
  "emails.variables.clubName": "Club",
  "emails.variables.parentEmail": "Ouder email",
  "emails.variables.documentType": "Document type",
  "emails.variables.date": "Datum",
  "emails.variables.time": "Tijd",
  "emails.variables.type": "Type",
  "emails.variables.admin": "Admin",
  "emails.variables.notes": "Notities",
  "emails.color.placeholder": "Kies een kleur",
  "emails.preview.mode": "Voorbeeld",
  "emails.edit.mode": "Bewerken",
  saving: "Opslaan...",
  save_changes: "Wijzigingen opslaan",
  "emails.guide.title": "Gebruikersgids",
  "emails.guide.instructions":
    "Gebruik de {variables} hieronder om automatisch uw e-mailinhoud aan te passen met ontvangergegevens.",
  "emails.guide.union.title": "Voor e-mails verzonden naar de Belgische Bond:",
  "emails.guide.union.attachments":
    "Bijgevoegde documenten (ongevalsaangifte, certificaat) worden automatisch als bijlagen toegevoegd",
  "emails.guide.union.format":
    "PDF-formaat wordt gebruikt voor alle documenten",
  "email.type.registration": "Registratieaanvraag",
  "email.type.selection": "Selectietest Aanvraag",
  "email.type.accident": "Ongevalsaangifte",
  "email.type.healing": "Genezingscertificaat",
  "email.type.waiver": "Aansprakelijkheidsverklaring",
  "email.type.registration_confirmed": "Registratiebevestiging",
  "email.type.selection_confirmed": "Testbevestiging",
  "email.type.accident_confirmed": "Ongevalbevestiging",
  "email.type.healing_confirmed": "Genezingsbevestiging",
  "email.type.waiver_confirmed": "Aansprakelijkheidsbevestiging",
  "email.type.accident_notify": "Ongevalmelding (Bond)",
  "email.type.healing_notify": "Genezingsmelding (Bond)",
  "email.type.appointment_scheduled": "Afspraakbevestiging",
  "email.type.appointment_cancelled": "Afspraakannulering",
  "emails.field.subject": "Onderwerp",
  "emails.field.text": "Tekst",
  "emails.type.requests": "Aanvragen",
  "emails.type.confirmations": "Bevestigingen",
  "emails.type.union": "Belgische Bond Verzendingen",
  "emails.type.appointments": "Afspraken",
  "email.type.accident-report": "Ongevalsaangifte",
  "email.type.healing-certificate": "Genezingscertificaat",
  "email.type.accident-notify": "Notification d'accident (Union)",
  "email.type.healing-notify": "Notification de guérison (Union)",
  "emails.category.requests": "Aanvragen",
  maintenance_active: "Onderhoud bezig",
  // Dans nl.ts, ajouter :
  "forms.maintenance.title": "Formulieren onderhoud",
  "forms.maintenance.description":
    "Schakel onderhoudsmodus voor specifieke formulieren in of uit.",
  "forms.maintenance.registration_desc":
    "Zet het inschrijvingsformulier in onderhoud.",
  "forms.maintenance.selection_desc":
    "Zet het selectietestformulier in onderhoud.",
  "forms.maintenance.accident_desc":
    "Zet het ongevallenformulier in onderhoud.",
  "forms.maintenance.waiver_desc": "Zet het vrijwaringsformulier in onderhoud.",
  brussels: "Brussel",
  toast_new_request_title: "Nieuw verzoek ontvangen",
  toast_new_request_description:
    "Een nieuw verzoek van het type {{type}} van {{name}} is aangekomen.",
  request_type_registration: "Inschrijvingsaanvraag",
  request_type_selection_tests: "Selectietesten",
  request_type_accident_report: "Ongevallenverklaring",
  request_type_responsibility_waiver: "Aansprakelijkheidsontheffing",
  status_unknown: "Onbekend",
  please_select_date_first: "Selecteer eerst een datum",
  admin_auto_assigned: "Automatisch toegewezen",
  today_appointments: "Vandaag",
  no_appointments_today: "Geen afspraken vandaag",
  appointment_singular: "afspraak",
  appointments_plural: "afspraken",
};
